use serde::Deserialize;
use std::path::{Path, PathBuf};

/// Minimal Cargo.toml structure for CMake generation.
#[derive(Deserialize)]
#[allow(dead_code)]
pub struct CargoToml {
    pub package: Package,
    #[serde(default)]
    pub lib: Option<LibTarget>,
    #[serde(default, rename = "bin")]
    pub bins: Option<Vec<BinTarget>>,
    #[serde(default)]
    pub dependencies: Option<toml::value::Table>,
}

/// Information about an external crate dependency.
#[derive(Debug, Clone)]
pub struct CrateDep {
    pub name: String,
    pub version: Option<String>,
    pub path: Option<String>,
    pub is_local: bool,
}

/// Extract dependency information from the parsed Cargo.toml.
pub fn extract_dependencies(cargo: &CargoToml) -> Vec<CrateDep> {
    let mut deps = Vec::new();

    if let Some(ref dep_table) = cargo.dependencies {
        for (name, value) in dep_table {
            match value {
                toml::Value::String(version) => {
                    deps.push(CrateDep {
                        name: name.clone(),
                        version: Some(version.clone()),
                        path: None,
                        is_local: false,
                    });
                }
                toml::Value::Table(t) => {
                    let version = t
                        .get("version")
                        .and_then(|v| v.as_str())
                        .map(|s| s.to_string());
                    let path = t
                        .get("path")
                        .and_then(|v| v.as_str())
                        .map(|s| s.to_string());
                    let is_local = path.is_some();
                    deps.push(CrateDep {
                        name: name.clone(),
                        version,
                        path,
                        is_local,
                    });
                }
                _ => {}
            }
        }
    }

    deps
}

#[derive(Deserialize)]
#[allow(dead_code)]
pub struct Package {
    pub name: String,
    #[serde(default = "default_version")]
    pub version: String,
    #[serde(default = "default_edition")]
    pub edition: String,
}

fn default_version() -> String {
    "0.1.0".to_string()
}
fn default_edition() -> String {
    "2021".to_string()
}

#[derive(Deserialize)]
#[allow(dead_code)]
pub struct LibTarget {
    #[serde(default)]
    pub name: Option<String>,
    #[serde(default)]
    pub path: Option<String>,
}

#[derive(Deserialize)]
pub struct BinTarget {
    pub name: String,
    #[serde(default)]
    pub path: Option<String>,
}

/// Map a Rust source file path to a C++20 module file path and module name.
/// `src/lib.rs` → (`crate_name.cppm`, `crate_name`)
/// `src/main.rs` → (`main.cppm`, `crate_name`)
/// `src/foo.rs` → (`crate_name.foo.cppm`, `crate_name.foo`)
/// `src/bar/mod.rs` → (`crate_name.bar.cppm`, `crate_name.bar`)
/// `src/bar/baz.rs` → (`crate_name.bar.baz.cppm`, `crate_name.bar.baz`)
pub fn map_rs_to_cppm(rs_path: &Path, crate_name: &str) -> (PathBuf, String) {
    let path_str = rs_path.to_string_lossy().replace('\\', "/");

    // Strip src/ prefix if present
    let relative = if let Some(stripped) = path_str.strip_prefix("src/") {
        stripped
    } else {
        &path_str
    };

    // Strip .rs extension
    let without_ext = relative.strip_suffix(".rs").unwrap_or(relative);

    match without_ext {
        "lib" | "main" => {
            let cppm = format!("{}.cppm", crate_name);
            (PathBuf::from(cppm), crate_name.to_string())
        }
        other => {
            // Replace mod.rs with parent directory name
            let normalized = if other.ends_with("/mod") {
                other.strip_suffix("/mod").unwrap_or(other)
            } else {
                other
            };

            // Convert path separators to dots for module name
            let module_name = format!("{}.{}", crate_name, normalized.replace('/', "."));
            let cppm = format!("{}.cppm", module_name);
            (PathBuf::from(cppm), module_name)
        }
    }
}

/// Generate a CMakeLists.txt from a parsed Cargo.toml.
pub fn generate_cmake(cargo: &CargoToml, source_files: &[PathBuf]) -> String {
    let mut out = String::new();
    let name = &cargo.package.name;
    let version = &cargo.package.version;

    // Header
    out.push_str("# Auto-generated by rusty-cpp-transpiler\n");
    out.push_str("# Do not edit manually.\n\n");
    out.push_str("cmake_minimum_required(VERSION 3.28)\n");
    out.push_str(&format!(
        "project({} VERSION {} LANGUAGES CXX)\n\n",
        name, version
    ));
    out.push_str("set(CMAKE_CXX_STANDARD 20)\n");
    out.push_str("set(CMAKE_CXX_STANDARD_REQUIRED ON)\n\n");

    // Include rusty-cpp headers
    out.push_str("# Include rusty-cpp headers\n");
    out.push_str("# Adjust this path to your rusty-cpp installation\n");
    out.push_str("# include_directories(${RUSTY_CPP_INCLUDE_DIR})\n\n");

    // Map source files to module files
    let module_files: Vec<(PathBuf, String)> = source_files
        .iter()
        .map(|f| map_rs_to_cppm(f, name))
        .collect();

    // Library target
    if cargo.lib.is_some() {
        let lib_name = cargo
            .lib
            .as_ref()
            .and_then(|l| l.name.clone())
            .unwrap_or_else(|| name.replace('-', "_"));

        out.push_str(&format!("add_library({}\n", lib_name));
        for (cppm, _) in &module_files {
            out.push_str(&format!("    {}\n", cppm.display()));
        }
        out.push_str(")\n\n");

        out.push_str(&format!(
            "target_sources({} PUBLIC FILE_SET CXX_MODULES FILES\n",
            lib_name
        ));
        for (cppm, _) in &module_files {
            out.push_str(&format!("    {}\n", cppm.display()));
        }
        out.push_str(")\n\n");
    }

    // Binary targets
    if let Some(bins) = &cargo.bins {
        for bin in bins {
            let bin_path = bin.path.as_deref().unwrap_or("src/main.rs");
            let (cppm, _) = map_rs_to_cppm(Path::new(bin_path), name);

            out.push_str(&format!("add_executable({}\n", bin.name));
            out.push_str(&format!("    {}\n", cppm.display()));
            out.push_str(")\n\n");
        }
    } else {
        // Default: if there's a src/main.rs, create a binary target
        let main_path = PathBuf::from("src/main.rs");
        if source_files.contains(&main_path) {
            let (cppm, _) = map_rs_to_cppm(&main_path, name);
            out.push_str(&format!("add_executable({}\n", name));
            out.push_str(&format!("    {}\n", cppm.display()));
            out.push_str(")\n\n");
        }
    }

    out
}

/// Parse a Cargo.toml file and return the parsed structure.
pub fn parse_cargo_toml(path: &Path) -> Result<CargoToml, String> {
    let content = std::fs::read_to_string(path)
        .map_err(|e| format!("Failed to read {}: {}", path.display(), e))?;
    toml::from_str(&content).map_err(|e| format!("Failed to parse Cargo.toml: {}", e))
}

/// Collect all .rs source files under src/.
pub fn collect_source_files(project_dir: &Path) -> Vec<PathBuf> {
    let src_dir = project_dir.join("src");
    if !src_dir.exists() {
        return vec![];
    }

    let mut files = Vec::new();
    collect_rs_files_recursive(&src_dir, &src_dir, &mut files);
    files.sort();
    files
}

fn collect_rs_files_recursive(base: &Path, dir: &Path, files: &mut Vec<PathBuf>) {
    if let Ok(entries) = std::fs::read_dir(dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                collect_rs_files_recursive(base, &path, files);
            } else if path.extension().is_some_and(|e| e == "rs") {
                // Make relative to project root (include "src/" prefix)
                if let Ok(relative) = path.strip_prefix(base.parent().unwrap_or(base)) {
                    files.push(relative.to_path_buf());
                }
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_map_lib_rs() {
        let (cppm, module) = map_rs_to_cppm(Path::new("src/lib.rs"), "my_crate");
        assert_eq!(cppm, PathBuf::from("my_crate.cppm"));
        assert_eq!(module, "my_crate");
    }

    #[test]
    fn test_map_main_rs() {
        let (cppm, module) = map_rs_to_cppm(Path::new("src/main.rs"), "my_crate");
        assert_eq!(cppm, PathBuf::from("my_crate.cppm"));
        assert_eq!(module, "my_crate");
    }

    #[test]
    fn test_map_submodule() {
        let (cppm, module) = map_rs_to_cppm(Path::new("src/foo.rs"), "my_crate");
        assert_eq!(cppm, PathBuf::from("my_crate.foo.cppm"));
        assert_eq!(module, "my_crate.foo");
    }

    #[test]
    fn test_map_nested_module() {
        let (cppm, module) = map_rs_to_cppm(Path::new("src/bar/baz.rs"), "my_crate");
        assert_eq!(cppm, PathBuf::from("my_crate.bar.baz.cppm"));
        assert_eq!(module, "my_crate.bar.baz");
    }

    #[test]
    fn test_map_mod_rs() {
        let (cppm, module) = map_rs_to_cppm(Path::new("src/bar/mod.rs"), "my_crate");
        assert_eq!(cppm, PathBuf::from("my_crate.bar.cppm"));
        assert_eq!(module, "my_crate.bar");
    }

    #[test]
    fn test_parse_cargo_toml() {
        let toml_str = r#"
            [package]
            name = "hello"
            version = "1.0.0"

            [[bin]]
            name = "hello"
            path = "src/main.rs"
        "#;
        let cargo: CargoToml = toml::from_str(toml_str).unwrap();
        assert_eq!(cargo.package.name, "hello");
        assert_eq!(cargo.package.version, "1.0.0");
        assert!(cargo.bins.is_some());
        assert_eq!(cargo.bins.as_ref().unwrap()[0].name, "hello");
    }

    #[test]
    fn test_generate_cmake_binary() {
        let cargo = CargoToml {
            package: Package {
                name: "hello".to_string(),
                version: "1.0.0".to_string(),
                edition: "2021".to_string(),
            },
            lib: None,
            bins: Some(vec![BinTarget {
                name: "hello".to_string(),
                path: Some("src/main.rs".to_string()),
            }]),
            dependencies: None,
        };
        let sources = vec![PathBuf::from("src/main.rs")];
        let cmake = generate_cmake(&cargo, &sources);
        assert!(cmake.contains("project(hello VERSION 1.0.0"));
        assert!(cmake.contains("add_executable(hello"));
        assert!(cmake.contains("hello.cppm"));
    }

    #[test]
    fn test_generate_cmake_library() {
        let cargo = CargoToml {
            package: Package {
                name: "my-lib".to_string(),
                version: "0.2.0".to_string(),
                edition: "2021".to_string(),
            },
            lib: Some(LibTarget {
                name: Some("my_lib".to_string()),
                path: None,
            }),
            bins: None,
            dependencies: None,
        };
        let sources = vec![PathBuf::from("src/lib.rs"), PathBuf::from("src/utils.rs")];
        let cmake = generate_cmake(&cargo, &sources);
        assert!(cmake.contains("project(my-lib VERSION 0.2.0"));
        assert!(cmake.contains("add_library(my_lib"));
        assert!(cmake.contains("my-lib.cppm"));
        assert!(cmake.contains("my-lib.utils.cppm"));
    }

    #[test]
    fn test_extract_dependencies_string_version() {
        let toml_str = r#"
            [package]
            name = "test"
            version = "0.1.0"
            [dependencies]
            serde = "1.0"
            rand = "0.8"
        "#;
        let cargo: CargoToml = toml::from_str(toml_str).unwrap();
        let deps = extract_dependencies(&cargo);
        assert_eq!(deps.len(), 2);
        assert!(
            deps.iter()
                .any(|d| d.name == "serde" && d.version.as_deref() == Some("1.0") && !d.is_local)
        );
        assert!(deps.iter().any(|d| d.name == "rand" && !d.is_local));
    }

    #[test]
    fn test_extract_dependencies_table_form() {
        let toml_str = r#"
            [package]
            name = "test"
            version = "0.1.0"
            [dependencies]
            serde = { version = "1.0", features = ["derive"] }
        "#;
        let cargo: CargoToml = toml::from_str(toml_str).unwrap();
        let deps = extract_dependencies(&cargo);
        assert_eq!(deps.len(), 1);
        assert_eq!(deps[0].name, "serde");
        assert_eq!(deps[0].version.as_deref(), Some("1.0"));
        assert!(!deps[0].is_local);
    }

    #[test]
    fn test_extract_dependencies_path() {
        let toml_str = r#"
            [package]
            name = "test"
            version = "0.1.0"
            [dependencies]
            my_lib = { path = "../my_lib" }
        "#;
        let cargo: CargoToml = toml::from_str(toml_str).unwrap();
        let deps = extract_dependencies(&cargo);
        assert_eq!(deps.len(), 1);
        assert_eq!(deps[0].name, "my_lib");
        assert_eq!(deps[0].path.as_deref(), Some("../my_lib"));
        assert!(deps[0].is_local);
    }

    #[test]
    fn test_extract_no_dependencies() {
        let toml_str = r#"
            [package]
            name = "test"
            version = "0.1.0"
        "#;
        let cargo: CargoToml = toml::from_str(toml_str).unwrap();
        let deps = extract_dependencies(&cargo);
        assert!(deps.is_empty());
    }
}
