use syn;

use crate::types;

/// Code generation context tracking indentation and output buffer.
pub struct CodeGen {
    output: String,
    indent: usize,
}

impl CodeGen {
    pub fn new() -> Self {
        Self {
            output: String::new(),
            indent: 0,
        }
    }

    pub fn into_output(self) -> String {
        self.output
    }

    fn writeln(&mut self, s: &str) {
        self.write_indent();
        self.output.push_str(s);
        self.output.push('\n');
    }

    fn write_indent(&mut self) {
        for _ in 0..self.indent {
            self.output.push_str("    ");
        }
    }

    fn newline(&mut self) {
        self.output.push('\n');
    }

    /// Emit a complete Rust file as C++ code.
    pub fn emit_file(&mut self, file: &syn::File) {
        self.writeln("// Auto-generated by rusty-cpp-transpiler");
        self.writeln("// Do not edit manually.");
        self.newline();
        self.writeln("#include <cstdint>");
        self.writeln("#include <cstddef>");
        self.newline();

        for item in &file.items {
            self.emit_item(item);
            self.newline();
        }
    }

    fn emit_item(&mut self, item: &syn::Item) {
        match item {
            syn::Item::Fn(f) => self.emit_function(f),
            syn::Item::Struct(s) => self.emit_struct(s),
            syn::Item::Enum(e) => self.emit_enum(e),
            syn::Item::Type(t) => self.emit_type_alias(t),
            syn::Item::Const(c) => self.emit_const(c),
            syn::Item::Static(s) => self.emit_static(s),
            syn::Item::Impl(i) => self.emit_impl_block(i),
            _ => {
                self.writeln(&format!("// TODO: unhandled item kind"));
            }
        }
    }

    fn emit_function(&mut self, f: &syn::ItemFn) {
        let name = &f.sig.ident;
        let return_type = self.map_return_type(&f.sig.output);
        let params = self.map_fn_params(&f.sig.inputs);

        self.writeln(&format!("{} {}({}) {{", return_type, name, params));
        self.indent += 1;
        self.emit_block(&f.block);
        self.indent -= 1;
        self.writeln("}");
    }

    fn emit_struct(&mut self, s: &syn::ItemStruct) {
        let name = &s.ident;
        self.writeln(&format!("struct {} {{", name));
        self.indent += 1;

        match &s.fields {
            syn::Fields::Named(fields) => {
                for field in &fields.named {
                    let field_name = field.ident.as_ref().unwrap();
                    let field_type = self.map_type(&field.ty);
                    self.writeln(&format!("{} {};", field_type, field_name));
                }
            }
            syn::Fields::Unnamed(fields) => {
                for (i, field) in fields.unnamed.iter().enumerate() {
                    let field_type = self.map_type(&field.ty);
                    self.writeln(&format!("{} _{};", field_type, i));
                }
            }
            syn::Fields::Unit => {}
        }

        self.indent -= 1;
        self.writeln("};");
    }

    fn emit_enum(&mut self, e: &syn::ItemEnum) {
        let name = &e.ident;
        let has_data = e.variants.iter().any(|v| !v.fields.is_empty());

        if has_data {
            // Enum with data → per-variant structs + std::variant
            self.writeln("// Algebraic data type");
            for variant in &e.variants {
                let vname = &variant.ident;
                match &variant.fields {
                    syn::Fields::Named(fields) => {
                        self.writeln(&format!("struct {}_{} {{", name, vname));
                        self.indent += 1;
                        for field in &fields.named {
                            let fname = field.ident.as_ref().unwrap();
                            let ftype = self.map_type(&field.ty);
                            self.writeln(&format!("{} {};", ftype, fname));
                        }
                        self.indent -= 1;
                        self.writeln("};");
                    }
                    syn::Fields::Unnamed(fields) => {
                        self.writeln(&format!("struct {}_{} {{", name, vname));
                        self.indent += 1;
                        for (i, field) in fields.unnamed.iter().enumerate() {
                            let ftype = self.map_type(&field.ty);
                            self.writeln(&format!("{} _{};", ftype, i));
                        }
                        self.indent -= 1;
                        self.writeln("};");
                    }
                    syn::Fields::Unit => {
                        self.writeln(&format!("struct {}_{} {{}};", name, vname));
                    }
                }
            }
            // Emit the variant alias
            let variant_list: Vec<String> = e
                .variants
                .iter()
                .map(|v| format!("{}_{}", name, v.ident))
                .collect();
            self.writeln(&format!(
                "using {} = std::variant<{}>;",
                name,
                variant_list.join(", ")
            ));
        } else {
            // C-like enum → enum class
            self.writeln(&format!("enum class {} {{", name));
            self.indent += 1;
            let variants: Vec<String> = e.variants.iter().map(|v| v.ident.to_string()).collect();
            self.writeln(&variants.join(",\n    "));
            self.indent -= 1;
            self.writeln("};");
        }
    }

    fn emit_type_alias(&mut self, t: &syn::ItemType) {
        let name = &t.ident;
        let target = self.map_type(&t.ty);
        self.writeln(&format!("using {} = {};", name, target));
    }

    fn emit_const(&mut self, c: &syn::ItemConst) {
        let name = &c.ident;
        let ty = self.map_type(&c.ty);
        let expr = self.emit_expr_to_string(&c.expr);
        self.writeln(&format!("constexpr {} {} = {};", ty, name, expr));
    }

    fn emit_static(&mut self, s: &syn::ItemStatic) {
        let name = &s.ident;
        let ty = self.map_type(&s.ty);
        let expr = self.emit_expr_to_string(&s.expr);
        self.writeln(&format!("static {} {} = {};", ty, name, expr));
    }

    fn emit_impl_block(&mut self, _i: &syn::ItemImpl) {
        self.writeln("// TODO: impl block (methods should be merged into struct)");
    }

    fn emit_block(&mut self, block: &syn::Block) {
        let stmts = &block.stmts;
        let len = stmts.len();

        for (i, stmt) in stmts.iter().enumerate() {
            let is_last = i == len - 1;
            self.emit_stmt(stmt, is_last);
        }
    }

    fn emit_stmt(&mut self, stmt: &syn::Stmt, is_tail: bool) {
        match stmt {
            syn::Stmt::Local(local) => self.emit_local(local),
            syn::Stmt::Expr(expr, semi) => {
                // Control flow expressions are emitted as statements directly
                if self.try_emit_control_flow(expr) {
                    return;
                }
                let expr_str = self.emit_expr_to_string(expr);
                if is_tail && semi.is_none() {
                    // Tail expression without semicolon → return
                    self.writeln(&format!("return {};", expr_str));
                } else {
                    self.writeln(&format!("{};", expr_str));
                }
            }
            syn::Stmt::Item(item) => self.emit_item(item),
            syn::Stmt::Macro(_) => {
                self.writeln("// TODO: macro invocation");
            }
        }
    }

    /// Try to emit an expression as a control flow statement.
    /// Returns true if it was handled, false if it should go through emit_expr_to_string.
    fn try_emit_control_flow(&mut self, expr: &syn::Expr) -> bool {
        match expr {
            syn::Expr::If(if_expr) => {
                self.emit_if(if_expr);
                true
            }
            syn::Expr::While(while_expr) => {
                self.emit_while(while_expr);
                true
            }
            syn::Expr::Loop(loop_expr) => {
                self.emit_loop(loop_expr);
                true
            }
            syn::Expr::ForLoop(for_expr) => {
                self.emit_for_loop(for_expr);
                true
            }
            syn::Expr::Block(block_expr) => {
                self.writeln("{");
                self.indent += 1;
                self.emit_block(&block_expr.block);
                self.indent -= 1;
                self.writeln("}");
                true
            }
            _ => false,
        }
    }

    fn emit_if(&mut self, if_expr: &syn::ExprIf) {
        self.emit_if_inner(if_expr, true);
    }

    fn emit_if_inner(&mut self, if_expr: &syn::ExprIf, first: bool) {
        let cond = self.emit_expr_to_string(&if_expr.cond);
        if first {
            self.writeln(&format!("if ({}) {{", cond));
        } else {
            // Continuation of else-if chain — "} else if (...) {" already on current line
            self.output.push_str(&format!("if ({}) {{\n", cond));
        }
        self.indent += 1;
        self.emit_block(&if_expr.then_branch);
        self.indent -= 1;

        if let Some((_, else_branch)) = &if_expr.else_branch {
            match else_branch.as_ref() {
                syn::Expr::If(else_if) => {
                    self.write_indent();
                    self.output.push_str("} else ");
                    self.emit_if_inner(else_if, false);
                    return;
                }
                syn::Expr::Block(block) => {
                    self.writeln("} else {");
                    self.indent += 1;
                    self.emit_block(&block.block);
                    self.indent -= 1;
                }
                _ => {
                    let else_str = self.emit_expr_to_string(else_branch);
                    self.writeln("} else {");
                    self.indent += 1;
                    self.writeln(&format!("{};", else_str));
                    self.indent -= 1;
                }
            }
        }
        self.writeln("}");
    }

    fn emit_while(&mut self, while_expr: &syn::ExprWhile) {
        let cond = self.emit_expr_to_string(&while_expr.cond);
        self.writeln(&format!("while ({}) {{", cond));
        self.indent += 1;
        self.emit_block(&while_expr.body);
        self.indent -= 1;
        self.writeln("}");
    }

    fn emit_loop(&mut self, loop_expr: &syn::ExprLoop) {
        // Check if this loop uses break-with-value.
        // If a loop has `break <expr>`, it's used as a value-producing loop.
        // We emit it as-is, and when used as `let x = loop { ... break val; }`,
        // the break-with-value is handled by emit_expr_to_string emitting `return val`.
        // The enclosing `let x = loop { ... }` should wrap in a lambda —
        // but that's handled at the let-binding level.
        self.writeln("while (true) {");
        self.indent += 1;
        self.emit_block(&loop_expr.body);
        self.indent -= 1;
        self.writeln("}");
    }

    fn emit_for_loop(&mut self, for_expr: &syn::ExprForLoop) {
        let pat = self.emit_pat_to_string(&for_expr.pat);
        let iter = self.emit_expr_to_string(&for_expr.expr);

        // Rust `for x in expr` → C++ `for (auto& x : expr)` or `for (auto x : expr)`
        // Use auto&& to handle both references and values correctly
        self.writeln(&format!("for (auto&& {} : {}) {{", pat, iter));
        self.indent += 1;
        self.emit_block(&for_expr.body);
        self.indent -= 1;
        self.writeln("}");
    }

    fn emit_pat_to_string(&self, pat: &syn::Pat) -> String {
        match pat {
            syn::Pat::Ident(pi) => pi.ident.to_string(),
            syn::Pat::Wild(_) => "_".to_string(),
            syn::Pat::Tuple(pt) => {
                let elems: Vec<String> = pt.elems.iter().map(|p| self.emit_pat_to_string(p)).collect();
                format!("[{}]", elems.join(", "))
            }
            syn::Pat::Reference(pr) => self.emit_pat_to_string(&pr.pat),
            _ => "/* TODO: pattern */".to_string(),
        }
    }

    fn emit_local(&mut self, local: &syn::Local) {
        let pat = &local.pat;

        match pat {
            syn::Pat::Ident(pat_ident) => {
                let name = &pat_ident.ident;
                let is_mut = pat_ident.mutability.is_some();

                let type_str = if let Some(ty) = get_local_type(local) {
                    self.map_type(ty)
                } else {
                    "auto".to_string()
                };

                let qualifier = if is_mut { "" } else { "const " };

                if let Some(init) = &local.init {
                    // Special case: `let x = loop { ... break val; }` → lambda wrapper
                    if let syn::Expr::Loop(loop_expr) = init.expr.as_ref() {
                        self.writeln(&format!(
                            "{}{} {} = [&]() {{",
                            qualifier, type_str, name
                        ));
                        self.indent += 1;
                        self.writeln("while (true) {");
                        self.indent += 1;
                        self.emit_block(&loop_expr.body);
                        self.indent -= 1;
                        self.writeln("}");
                        self.indent -= 1;
                        self.writeln("}();");
                    } else {
                        let expr_str = self.emit_expr_to_string(&init.expr);
                        self.writeln(&format!(
                            "{}{} {} = {};",
                            qualifier, type_str, name, expr_str
                        ));
                    }
                } else {
                    self.writeln(&format!("{}{} {};", qualifier, type_str, name));
                }
            }
            _ => {
                self.writeln("// TODO: complex pattern binding");
            }
        }
    }

    fn emit_expr_to_string(&self, expr: &syn::Expr) -> String {
        match expr {
            syn::Expr::Lit(lit) => self.emit_lit(&lit.lit),
            syn::Expr::Path(path) => self.emit_path_to_string(&path.path),
            syn::Expr::Binary(bin) => {
                let left = self.emit_expr_to_string(&bin.left);
                let op = self.emit_binop(&bin.op);
                let right = self.emit_expr_to_string(&bin.right);
                format!("{} {} {}", left, op, right)
            }
            syn::Expr::Unary(un) => {
                let operand = self.emit_expr_to_string(&un.expr);
                match un.op {
                    syn::UnOp::Neg(_) => format!("-{}", operand),
                    syn::UnOp::Not(_) => format!("!{}", operand),
                    syn::UnOp::Deref(_) => format!("*{}", operand),
                    _ => format!("/* unknown unary */ {}", operand),
                }
            }
            syn::Expr::Reference(r) => {
                let inner = self.emit_expr_to_string(&r.expr);
                format!("&{}", inner)
            }
            syn::Expr::Call(call) => {
                let func = self.emit_expr_to_string(&call.func);
                let args: Vec<String> = call
                    .args
                    .iter()
                    .map(|a| self.emit_expr_to_string(a))
                    .collect();
                format!("{}({})", func, args.join(", "))
            }
            syn::Expr::MethodCall(mc) => {
                let receiver = self.emit_expr_to_string(&mc.receiver);
                let method = &mc.method;
                let args: Vec<String> = mc
                    .args
                    .iter()
                    .map(|a| self.emit_expr_to_string(a))
                    .collect();
                format!("{}.{}({})", receiver, method, args.join(", "))
            }
            syn::Expr::Field(f) => {
                let base = self.emit_expr_to_string(&f.base);
                match &f.member {
                    syn::Member::Named(ident) => format!("{}.{}", base, ident),
                    syn::Member::Unnamed(idx) => format!("{}._{}", base, idx.index),
                }
            }
            syn::Expr::If(if_expr) => {
                // If used as an expression (e.g., `let x = if c { 1 } else { 2 };`)
                // → C++ ternary when simple
                if let Some((_, else_branch)) = &if_expr.else_branch {
                    let cond = self.emit_expr_to_string(&if_expr.cond);
                    if let (Some(then_val), Some(else_val)) =
                        (self.block_single_expr(&if_expr.then_branch), self.expr_single_value(else_branch))
                    {
                        return format!("({} ? {} : {})", cond, then_val, else_val);
                    }
                }
                format!("/* TODO: if-expression */")
            }
            syn::Expr::Break(brk) => {
                match &brk.expr {
                    Some(val) => {
                        let v = self.emit_expr_to_string(val);
                        format!("return {}", v)  // break-with-value inside lambda wrapper
                    }
                    None => "break".to_string(),
                }
            }
            syn::Expr::Continue(_) => "continue".to_string(),
            syn::Expr::Range(range) => {
                // Rust range `a..b` → we need a range helper; for now emit for use in for-loops
                let start = range.start.as_ref().map(|e| self.emit_expr_to_string(e)).unwrap_or_default();
                let end = range.end.as_ref().map(|e| self.emit_expr_to_string(e)).unwrap_or_default();
                format!("rusty::range({}, {})", start, end)
            }
            syn::Expr::Closure(closure) => {
                let params: Vec<String> = closure.inputs.iter().map(|p| {
                    self.emit_pat_to_string(p)
                }).collect();
                let body = self.emit_expr_to_string(&closure.body);
                format!("[&](auto {}) {{ return {}; }}", params.join(", auto "), body)
            }
            syn::Expr::Return(ret) => match &ret.expr {
                Some(e) => {
                    let val = self.emit_expr_to_string(e);
                    format!("return {}", val)
                }
                None => "return".to_string(),
            },
            syn::Expr::Assign(a) => {
                let left = self.emit_expr_to_string(&a.left);
                let right = self.emit_expr_to_string(&a.right);
                format!("{} = {}", left, right)
            }
            syn::Expr::Struct(s) => {
                let name = self.emit_path_to_string(&s.path);
                let fields: Vec<String> = s
                    .fields
                    .iter()
                    .map(|f| {
                        let val = self.emit_expr_to_string(&f.expr);
                        let member_name = match &f.member {
                            syn::Member::Named(ident) => ident.to_string(),
                            syn::Member::Unnamed(idx) => format!("_{}", idx.index),
                        };
                        format!(".{} = {}", member_name, val)
                    })
                    .collect();
                format!("{}{{{}}}", name, fields.join(", "))
            }
            syn::Expr::Paren(p) => {
                let inner = self.emit_expr_to_string(&p.expr);
                format!("({})", inner)
            }
            syn::Expr::Cast(c) => {
                let expr = self.emit_expr_to_string(&c.expr);
                let ty = self.map_type(&c.ty);
                format!("static_cast<{}>({})", ty, expr)
            }
            syn::Expr::Index(idx) => {
                let base = self.emit_expr_to_string(&idx.expr);
                let index = self.emit_expr_to_string(&idx.index);
                format!("{}[{}]", base, index)
            }
            _ => format!("/* TODO: expr */"),
        }
    }

    fn emit_lit(&self, lit: &syn::Lit) -> String {
        match lit {
            syn::Lit::Int(i) => i.base10_digits().to_string(),
            syn::Lit::Float(f) => f.base10_digits().to_string(),
            syn::Lit::Bool(b) => if b.value { "true" } else { "false" }.to_string(),
            syn::Lit::Str(s) => format!("\"{}\"", s.value()),
            syn::Lit::Char(c) => format!("U'{}'", c.value()),
            syn::Lit::Byte(b) => format!("static_cast<uint8_t>({})", b.value()),
            _ => "/* TODO: literal */".to_string(),
        }
    }

    fn emit_binop(&self, op: &syn::BinOp) -> &'static str {
        match op {
            syn::BinOp::Add(_) => "+",
            syn::BinOp::Sub(_) => "-",
            syn::BinOp::Mul(_) => "*",
            syn::BinOp::Div(_) => "/",
            syn::BinOp::Rem(_) => "%",
            syn::BinOp::And(_) => "&&",
            syn::BinOp::Or(_) => "||",
            syn::BinOp::BitXor(_) => "^",
            syn::BinOp::BitAnd(_) => "&",
            syn::BinOp::BitOr(_) => "|",
            syn::BinOp::Shl(_) => "<<",
            syn::BinOp::Shr(_) => ">>",
            syn::BinOp::Eq(_) => "==",
            syn::BinOp::Lt(_) => "<",
            syn::BinOp::Le(_) => "<=",
            syn::BinOp::Ne(_) => "!=",
            syn::BinOp::Ge(_) => ">=",
            syn::BinOp::Gt(_) => ">",
            syn::BinOp::AddAssign(_) => "+=",
            syn::BinOp::SubAssign(_) => "-=",
            syn::BinOp::MulAssign(_) => "*=",
            syn::BinOp::DivAssign(_) => "/=",
            syn::BinOp::RemAssign(_) => "%=",
            syn::BinOp::BitXorAssign(_) => "^=",
            syn::BinOp::BitAndAssign(_) => "&=",
            syn::BinOp::BitOrAssign(_) => "|=",
            syn::BinOp::ShlAssign(_) => "<<=",
            syn::BinOp::ShrAssign(_) => ">>=",
            _ => "/* unknown op */",
        }
    }

    fn emit_path_to_string(&self, path: &syn::Path) -> String {
        let segments: Vec<String> = path.segments.iter().map(|s| s.ident.to_string()).collect();
        let joined = segments.join("::");

        // Try mapping as a standard type
        if let Some((cpp_type, _)) = types::map_std_type(&joined) {
            return cpp_type.to_string();
        }

        // Try as primitive
        if segments.len() == 1 {
            if let Some(cpp_prim) = types::map_primitive_type(&segments[0]) {
                return cpp_prim.to_string();
            }
        }

        // Replace Rust's :: with C++ ::
        joined
    }

    fn map_type(&self, ty: &syn::Type) -> String {
        match ty {
            syn::Type::Path(tp) => {
                let path_str = self.emit_path_to_string(&tp.path);

                // Check if the last segment has generic arguments
                if let Some(last_seg) = tp.path.segments.last() {
                    if let syn::PathArguments::AngleBracketed(args) = &last_seg.arguments {
                        let type_args: Vec<String> = args
                            .args
                            .iter()
                            .filter_map(|arg| {
                                if let syn::GenericArgument::Type(t) = arg {
                                    Some(self.map_type(t))
                                } else {
                                    None
                                }
                            })
                            .collect();

                        if !type_args.is_empty() {
                            // Re-map the base without the args we already processed
                            let base = {
                                let segs: Vec<String> = tp
                                    .path
                                    .segments
                                    .iter()
                                    .map(|s| s.ident.to_string())
                                    .collect();
                                let joined = segs.join("::");
                                if let Some((cpp, _)) = types::map_std_type(&joined) {
                                    cpp.to_string()
                                } else if segs.len() == 1 {
                                    types::map_primitive_type(&segs[0])
                                        .map(|s| s.to_string())
                                        .unwrap_or(joined)
                                } else {
                                    joined
                                }
                            };
                            return format!("{}<{}>", base, type_args.join(", "));
                        }
                    }
                }

                path_str
            }
            syn::Type::Reference(r) => {
                let inner = self.map_type(&r.elem);
                if r.mutability.is_some() {
                    format!("{}&", inner)
                } else {
                    format!("const {}&", inner)
                }
            }
            syn::Type::Ptr(p) => {
                let inner = self.map_type(&p.elem);
                if p.mutability.is_some() {
                    format!("{}*", inner)
                } else {
                    format!("const {}*", inner)
                }
            }
            syn::Type::Tuple(t) => {
                if t.elems.is_empty() {
                    "void".to_string()
                } else {
                    let elems: Vec<String> = t.elems.iter().map(|e| self.map_type(e)).collect();
                    format!("std::tuple<{}>", elems.join(", "))
                }
            }
            syn::Type::Array(a) => {
                let elem = self.map_type(&a.elem);
                let len = self.emit_expr_to_string(&a.len);
                format!("std::array<{}, {}>", elem, len)
            }
            syn::Type::Slice(s) => {
                let elem = self.map_type(&s.elem);
                format!("std::span<const {}>", elem)
            }
            syn::Type::Never(_) => "[[noreturn]] void".to_string(),
            syn::Type::Infer(_) => "auto".to_string(),
            _ => "/* TODO: type */".to_string(),
        }
    }

    /// If a block contains exactly one expression (tail expr), return its string form.
    fn block_single_expr(&self, block: &syn::Block) -> Option<String> {
        if block.stmts.len() == 1 {
            if let syn::Stmt::Expr(expr, None) = &block.stmts[0] {
                return Some(self.emit_expr_to_string(expr));
            }
        }
        None
    }

    /// Extract the single value from an else branch expression.
    fn expr_single_value(&self, expr: &syn::Expr) -> Option<String> {
        match expr {
            syn::Expr::Block(block) => self.block_single_expr(&block.block),
            _ => Some(self.emit_expr_to_string(expr)),
        }
    }

    fn map_return_type(&self, output: &syn::ReturnType) -> String {
        match output {
            syn::ReturnType::Default => "void".to_string(),
            syn::ReturnType::Type(_, ty) => self.map_type(ty),
        }
    }

    fn map_fn_params(&self, inputs: &syn::punctuated::Punctuated<syn::FnArg, syn::token::Comma>) -> String {
        let params: Vec<String> = inputs
            .iter()
            .map(|arg| match arg {
                syn::FnArg::Typed(pat_type) => {
                    let ty = self.map_type(&pat_type.ty);
                    let name = match pat_type.pat.as_ref() {
                        syn::Pat::Ident(pi) => pi.ident.to_string(),
                        _ => "_".to_string(),
                    };
                    format!("{} {}", ty, name)
                }
                syn::FnArg::Receiver(_) => "/* self */".to_string(),
            })
            .collect();
        params.join(", ")
    }
}

/// Extract the type annotation from a local variable binding, if present.
fn get_local_type(local: &syn::Local) -> Option<&syn::Type> {
    match &local.pat {
        syn::Pat::Type(pt) => Some(&pt.ty),
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn transpile_str(rust_code: &str) -> String {
        let file: syn::File = syn::parse_str(rust_code).unwrap();
        let mut cg = CodeGen::new();
        cg.emit_file(&file);
        cg.into_output()
    }

    #[test]
    fn test_simple_function() {
        let out = transpile_str("fn add(a: i32, b: i32) -> i32 { a + b }");
        assert!(out.contains("int32_t add(int32_t a, int32_t b)"));
        assert!(out.contains("return a + b;"));
    }

    #[test]
    fn test_void_function() {
        let out = transpile_str("fn noop() {}");
        assert!(out.contains("void noop()"));
    }

    #[test]
    fn test_struct() {
        let out = transpile_str("struct Point { x: f64, y: f64 }");
        assert!(out.contains("struct Point {"));
        assert!(out.contains("double x;"));
        assert!(out.contains("double y;"));
    }

    #[test]
    fn test_const() {
        let out = transpile_str("const MAX: i32 = 100;");
        assert!(out.contains("constexpr int32_t MAX = 100;"));
    }

    #[test]
    fn test_c_like_enum() {
        let out = transpile_str("enum Color { Red, Green, Blue }");
        assert!(out.contains("enum class Color {"));
        assert!(out.contains("Red"));
        assert!(out.contains("Green"));
        assert!(out.contains("Blue"));
    }

    #[test]
    fn test_enum_with_data() {
        let out = transpile_str(
            "enum Shape { Circle(f64), Rect { w: f64, h: f64 }, None }",
        );
        assert!(out.contains("struct Shape_Circle {"));
        assert!(out.contains("double _0;"));
        assert!(out.contains("struct Shape_Rect {"));
        assert!(out.contains("double w;"));
        assert!(out.contains("struct Shape_None {}"));
        assert!(out.contains("using Shape = std::variant<"));
    }

    #[test]
    fn test_type_alias() {
        let out = transpile_str("type Num = i32;");
        assert!(out.contains("using Num = int32_t;"));
    }

    #[test]
    fn test_let_binding_immutable() {
        let out = transpile_str("fn f() { let x = 5; }");
        assert!(out.contains("const auto x = 5;"));
    }

    #[test]
    fn test_let_binding_mutable() {
        let out = transpile_str("fn f() { let mut x = 5; }");
        assert!(out.contains("auto x = 5;"));
    }

    #[test]
    fn test_std_type_mapping() {
        let out = transpile_str("fn f(v: Vec<i32>) {}");
        assert!(out.contains("rusty::Vec<int32_t>"));
    }

    #[test]
    fn test_reference_types() {
        let out = transpile_str("fn f(a: &i32, b: &mut i32) {}");
        assert!(out.contains("const int32_t&"));
        assert!(out.contains("int32_t&"));
    }

    #[test]
    fn test_option_type() {
        let out = transpile_str("fn f() -> Option<i32> { 42 }");
        assert!(out.contains("rusty::Option<int32_t>"));
    }

    #[test]
    fn test_tuple_return() {
        let out = transpile_str("fn f() -> (i32, f64) { (1, 2.0) }");
        assert!(out.contains("std::tuple<int32_t, double>"));
    }

    #[test]
    fn test_array_type() {
        let out = transpile_str("fn f(a: [i32; 5]) {}");
        assert!(out.contains("std::array<int32_t, 5>"));
    }

    #[test]
    fn test_unit_return_is_void() {
        let out = transpile_str("fn f() -> () {}");
        assert!(out.contains("void f()"));
    }

    #[test]
    fn test_binary_operators() {
        let out = transpile_str("fn f() -> i32 { 1 + 2 * 3 }");
        assert!(out.contains("return 1 + 2 * 3;"));
    }

    #[test]
    fn test_static_var() {
        let out = transpile_str("static COUNT: i32 = 0;");
        assert!(out.contains("static int32_t COUNT = 0;"));
    }

    #[test]
    fn test_cast() {
        let out = transpile_str("fn f() { let x = 5 as f64; }");
        assert!(out.contains("static_cast<double>(5)"));
    }

    #[test]
    fn test_string_literal() {
        let out = transpile_str(r#"fn f() { let s = "hello"; }"#);
        assert!(out.contains("\"hello\""));
    }

    #[test]
    fn test_bool_literal() {
        let out = transpile_str("fn f() -> bool { true }");
        assert!(out.contains("return true;"));
    }

    #[test]
    fn test_method_call() {
        let out = transpile_str("fn f() { v.push(1); }");
        assert!(out.contains("v.push(1);"));
    }

    #[test]
    fn test_field_access() {
        let out = transpile_str("fn f() -> f64 { p.x }");
        assert!(out.contains("return p.x;"));
    }

    #[test]
    fn test_index_expr() {
        let out = transpile_str("fn f() { let x = arr[0]; }");
        assert!(out.contains("arr[0]"));
    }

    #[test]
    fn test_struct_literal() {
        let out = transpile_str("fn f() -> Point { Point { x: 1.0, y: 2.0 } }");
        assert!(out.contains("Point{"));
        assert!(out.contains(".x = 1.0"));
        assert!(out.contains(".y = 2.0"));
    }

    #[test]
    fn test_result_type() {
        let out = transpile_str("fn f() -> Result<i32, String> { Ok(1) }");
        assert!(out.contains("rusty::Result<int32_t, rusty::String>"));
    }

    #[test]
    fn test_box_type() {
        let out = transpile_str("fn f(b: Box<i32>) {}");
        assert!(out.contains("rusty::Box<int32_t>"));
    }

    #[test]
    fn test_hashmap_type() {
        let out = transpile_str("fn f(m: HashMap<String, i32>) {}");
        assert!(out.contains("rusty::HashMap<rusty::String, int32_t>"));
    }

    // ── Control flow tests ──────────────────────────────────────

    #[test]
    fn test_if_simple() {
        let out = transpile_str("fn f(x: i32) { if x > 0 { x; } }");
        assert!(out.contains("if (x > 0) {"));
        assert!(out.contains("x;"));
        assert!(out.contains("}"));
    }

    #[test]
    fn test_if_else() {
        let out = transpile_str("fn f(x: i32) { if x > 0 { x; } else { 0; } }");
        assert!(out.contains("if (x > 0) {"));
        assert!(out.contains("} else {"));
    }

    #[test]
    fn test_if_else_if() {
        let out = transpile_str(
            "fn f(x: i32) { if x > 0 { 1; } else if x < 0 { 2; } else { 0; } }",
        );
        assert!(out.contains("if (x > 0) {"));
        assert!(out.contains("} else if (x < 0) {"));
        assert!(out.contains("} else {"));
    }

    #[test]
    fn test_if_tail_expr_returns() {
        // When if/else is the tail expression of a function, each branch gets `return`
        let out = transpile_str("fn f(c: bool) -> i32 { if c { 1 } else { 0 } }");
        assert!(out.contains("if (c) {"));
        assert!(out.contains("return 1;"));
        assert!(out.contains("return 0;"));
    }

    #[test]
    fn test_if_expr_as_ternary() {
        // When if/else is used in a let binding with simple branches → ternary
        let out = transpile_str("fn f(c: bool) { let x = if c { 1 } else { 0 }; }");
        assert!(out.contains("(c ? 1 : 0)"));
    }

    #[test]
    fn test_while_loop() {
        let out = transpile_str("fn f() { let mut x = 10; while x > 0 { x = x - 1; } }");
        assert!(out.contains("while (x > 0) {"));
    }

    #[test]
    fn test_infinite_loop() {
        let out = transpile_str("fn f() { loop { break; } }");
        assert!(out.contains("while (true) {"));
        assert!(out.contains("break;"));
    }

    #[test]
    fn test_for_in_range() {
        let out = transpile_str("fn f() { for i in 0..10 { i; } }");
        assert!(out.contains("for (auto&& i : rusty::range(0, 10)) {"));
    }

    #[test]
    fn test_for_in_variable() {
        let out = transpile_str("fn f() { for x in items { x; } }");
        assert!(out.contains("for (auto&& x : items) {"));
    }

    #[test]
    fn test_break_continue() {
        let out = transpile_str("fn f() { loop { if true { break; } continue; } }");
        assert!(out.contains("break;"));
        assert!(out.contains("continue;"));
    }

    #[test]
    fn test_loop_break_with_value() {
        let out = transpile_str(
            "fn f() { let result = loop { if true { break 42; } }; }",
        );
        assert!(out.contains("[&]()"));
        assert!(out.contains("while (true)"));
        assert!(out.contains("return 42;"));
        assert!(out.contains("}();"));
    }

    #[test]
    fn test_nested_if_in_loop() {
        let out = transpile_str(
            "fn f() { while true { if true { break; } else { continue; } } }",
        );
        assert!(out.contains("while (true) {"));
        assert!(out.contains("if (true) {"));
        assert!(out.contains("break;"));
        assert!(out.contains("} else {"));
        assert!(out.contains("continue;"));
    }

    #[test]
    fn test_nested_loops() {
        let out = transpile_str(
            "fn f() { for i in 0..5 { for j in 0..5 { i; } } }",
        );
        assert!(out.contains("for (auto&& i : rusty::range(0, 5)) {"));
        assert!(out.contains("for (auto&& j : rusty::range(0, 5)) {"));
    }

    #[test]
    fn test_if_with_let_binding() {
        let out = transpile_str("fn f() { if true { let x = 1; x; } }");
        assert!(out.contains("if (true) {"));
        assert!(out.contains("const auto x = 1;"));
    }

    #[test]
    fn test_closure_basic() {
        let out = transpile_str("fn f() { let add = |a, b| a + b; }");
        assert!(out.contains("[&]"));
        assert!(out.contains("return a + b;"));
    }
}
