use std::collections::HashMap;
use syn;

use crate::types;

/// Code generation context tracking indentation and output buffer.
pub struct CodeGen {
    output: String,
    indent: usize,
    /// Collected impl blocks indexed by type name.
    /// Populated during the first pass of emit_file.
    impl_blocks: HashMap<String, Vec<syn::ImplItem>>,
    /// Current struct name when emitting methods inside a struct.
    /// Used to resolve `Self` type references.
    current_struct: Option<String>,
    /// Set of variable names that are reassigned in the current block.
    /// Used for reference rebinding detection: if a `let mut r: &T` variable
    /// is reassigned, emit it as a pointer instead of a reference.
    reassigned_vars: std::collections::HashSet<String>,
}

impl CodeGen {
    pub fn new() -> Self {
        Self {
            output: String::new(),
            indent: 0,
            impl_blocks: HashMap::new(),
            current_struct: None,
            reassigned_vars: std::collections::HashSet::new(),
        }
    }

    pub fn into_output(self) -> String {
        self.output
    }

    fn writeln(&mut self, s: &str) {
        self.write_indent();
        self.output.push_str(s);
        self.output.push('\n');
    }

    fn write_indent(&mut self) {
        for _ in 0..self.indent {
            self.output.push_str("    ");
        }
    }

    fn newline(&mut self) {
        self.output.push('\n');
    }

    /// Emit a complete Rust file as C++ code.
    /// Uses a two-pass approach: first collects impl blocks, then emits items
    /// with methods merged into their struct definitions.
    pub fn emit_file(&mut self, file: &syn::File) {
        // Pass 1: collect all impl blocks by type name
        for item in &file.items {
            if let syn::Item::Impl(impl_block) = item {
                if let syn::Type::Path(tp) = impl_block.self_ty.as_ref() {
                    let type_name = tp
                        .path
                        .segments
                        .iter()
                        .map(|s| s.ident.to_string())
                        .collect::<Vec<_>>()
                        .join("::");
                    let entry = self.impl_blocks.entry(type_name).or_default();
                    for impl_item in &impl_block.items {
                        entry.push(impl_item.clone());
                    }
                }
            }
        }

        // Pass 2: emit all items
        self.writeln("// Auto-generated by rusty-cpp-transpiler");
        self.writeln("// Do not edit manually.");
        self.newline();
        self.writeln("#include <cstdint>");
        self.writeln("#include <cstddef>");
        self.newline();

        for item in &file.items {
            // Skip impl blocks — they've been merged into structs
            if matches!(item, syn::Item::Impl(_)) {
                continue;
            }
            self.emit_item(item);
            self.newline();
        }
    }

    fn emit_item(&mut self, item: &syn::Item) {
        match item {
            syn::Item::Fn(f) => self.emit_function(f),
            syn::Item::Struct(s) => self.emit_struct(s),
            syn::Item::Enum(e) => self.emit_enum(e),
            syn::Item::Type(t) => self.emit_type_alias(t),
            syn::Item::Const(c) => self.emit_const(c),
            syn::Item::Static(s) => self.emit_static(s),
            syn::Item::Impl(i) => self.emit_impl_block(i),
            syn::Item::ForeignMod(fm) => self.emit_foreign_mod(fm),
            _ => {
                self.writeln("// TODO: unhandled item kind");
            }
        }
    }

    fn emit_function(&mut self, f: &syn::ItemFn) {
        let name = escape_cpp_keyword(&f.sig.ident.to_string());
        let return_type = self.map_return_type(&f.sig.output);
        let params = self.map_fn_params(&f.sig.inputs);

        // Check for extern "C" ABI
        let abi_prefix = if let Some(abi) = &f.sig.abi {
            if let Some(name) = &abi.name {
                if name.value() == "C" {
                    "extern \"C\" "
                } else {
                    ""
                }
            } else {
                "extern \"C\" "
            }
        } else {
            ""
        };

        self.writeln(&format!("{}{} {}({}) {{", abi_prefix, return_type, name, params));
        self.indent += 1;
        self.emit_block(&f.block);
        self.indent -= 1;
        self.writeln("}");
    }

    fn emit_foreign_mod(&mut self, fm: &syn::ItemForeignMod) {
        // extern "C" { fn foo(...); } → extern "C" { declarations }
        let abi = if let Some(abi_name) = &fm.abi.name {
            format!("\"{}\"", abi_name.value())
        } else {
            "\"C\"".to_string()
        };
        self.writeln(&format!("extern {} {{", abi));
        self.indent += 1;
        for item in &fm.items {
            if let syn::ForeignItem::Fn(f) = item {
                let name = &f.sig.ident;
                let return_type = self.map_return_type(&f.sig.output);
                let params = self.map_fn_params(&f.sig.inputs);
                self.writeln(&format!("{} {}({});", return_type, name, params));
            }
        }
        self.indent -= 1;
        self.writeln("}");
    }

    fn emit_struct(&mut self, s: &syn::ItemStruct) {
        let name = &s.ident;
        let name_str = name.to_string();
        self.writeln(&format!("struct {} {{", name));
        self.indent += 1;

        // Emit fields
        match &s.fields {
            syn::Fields::Named(fields) => {
                for field in &fields.named {
                    let field_name = field.ident.as_ref().unwrap();
                    let field_type = self.map_type(&field.ty);
                    self.writeln(&format!("{} {};", field_type, field_name));
                }
            }
            syn::Fields::Unnamed(fields) => {
                for (i, field) in fields.unnamed.iter().enumerate() {
                    let field_type = self.map_type(&field.ty);
                    self.writeln(&format!("{} _{};", field_type, i));
                }
            }
            syn::Fields::Unit => {}
        }

        // Emit methods from impl blocks (merged)
        if let Some(methods) = self.impl_blocks.remove(&name_str) {
            if !matches!(&s.fields, syn::Fields::Unit if methods.is_empty()) {
                self.newline();
            }
            self.current_struct = Some(name_str.clone());
            for impl_item in &methods {
                self.emit_impl_item(impl_item);
            }
            self.current_struct = None;
        }

        self.indent -= 1;
        self.writeln("};");
    }

    fn emit_enum(&mut self, e: &syn::ItemEnum) {
        let name = &e.ident;
        let has_data = e.variants.iter().any(|v| !v.fields.is_empty());

        if has_data {
            // Enum with data → per-variant structs + std::variant
            self.writeln("// Algebraic data type");
            for variant in &e.variants {
                let vname = &variant.ident;
                match &variant.fields {
                    syn::Fields::Named(fields) => {
                        self.writeln(&format!("struct {}_{} {{", name, vname));
                        self.indent += 1;
                        for field in &fields.named {
                            let fname = field.ident.as_ref().unwrap();
                            let ftype = self.map_type(&field.ty);
                            self.writeln(&format!("{} {};", ftype, fname));
                        }
                        self.indent -= 1;
                        self.writeln("};");
                    }
                    syn::Fields::Unnamed(fields) => {
                        self.writeln(&format!("struct {}_{} {{", name, vname));
                        self.indent += 1;
                        for (i, field) in fields.unnamed.iter().enumerate() {
                            let ftype = self.map_type(&field.ty);
                            self.writeln(&format!("{} _{};", ftype, i));
                        }
                        self.indent -= 1;
                        self.writeln("};");
                    }
                    syn::Fields::Unit => {
                        self.writeln(&format!("struct {}_{} {{}};", name, vname));
                    }
                }
            }
            // Emit the variant alias
            let variant_list: Vec<String> = e
                .variants
                .iter()
                .map(|v| format!("{}_{}", name, v.ident))
                .collect();
            self.writeln(&format!(
                "using {} = std::variant<{}>;",
                name,
                variant_list.join(", ")
            ));
        } else {
            // C-like enum → enum class
            self.writeln(&format!("enum class {} {{", name));
            self.indent += 1;
            let variants: Vec<String> = e.variants.iter().map(|v| v.ident.to_string()).collect();
            self.writeln(&variants.join(",\n    "));
            self.indent -= 1;
            self.writeln("};");
        }
    }

    fn emit_type_alias(&mut self, t: &syn::ItemType) {
        let name = &t.ident;
        let target = self.map_type(&t.ty);
        self.writeln(&format!("using {} = {};", name, target));
    }

    fn emit_const(&mut self, c: &syn::ItemConst) {
        let name = &c.ident;
        let ty = self.map_type(&c.ty);
        let expr = self.emit_expr_to_string(&c.expr);
        self.writeln(&format!("constexpr {} {} = {};", ty, name, expr));
    }

    fn emit_static(&mut self, s: &syn::ItemStatic) {
        let name = &s.ident;
        let ty = self.map_type(&s.ty);
        let expr = self.emit_expr_to_string(&s.expr);
        self.writeln(&format!("static {} {} = {};", ty, name, expr));
    }

    fn emit_impl_block(&mut self, i: &syn::ItemImpl) {
        // This is called for impl blocks whose struct wasn't found in the same file.
        // Emit methods as free-standing functions (fallback).
        let type_name = if let syn::Type::Path(tp) = i.self_ty.as_ref() {
            tp.path
                .segments
                .iter()
                .map(|s| s.ident.to_string())
                .collect::<Vec<_>>()
                .join("::")
        } else {
            "UnknownType".to_string()
        };

        self.writeln(&format!("// Methods for {}", type_name));
        for item in &i.items {
            self.emit_impl_item(item);
        }
    }

    fn emit_impl_item(&mut self, item: &syn::ImplItem) {
        match item {
            syn::ImplItem::Fn(method) => self.emit_method(method),
            syn::ImplItem::Const(c) => {
                let name = &c.ident;
                let ty = self.map_type(&c.ty);
                let expr = self.emit_expr_to_string(&c.expr);
                self.writeln(&format!("static constexpr {} {} = {};", ty, name, expr));
            }
            syn::ImplItem::Type(t) => {
                let name = &t.ident;
                let ty = self.map_type(&t.ty);
                self.writeln(&format!("using {} = {};", name, ty));
            }
            _ => {
                self.writeln("// TODO: unhandled impl item");
            }
        }
    }

    fn emit_method(&mut self, method: &syn::ImplItemFn) {
        let name = escape_cpp_keyword(&method.sig.ident.to_string());
        let return_type = self.map_return_type(&method.sig.output);

        // Analyze receiver to determine method kind
        let (qualifier, is_static) = match method.sig.inputs.first() {
            Some(syn::FnArg::Receiver(recv)) => {
                if recv.reference.is_some() {
                    if recv.mutability.is_some() {
                        // &mut self → non-const method
                        ("", false)
                    } else {
                        // &self → const method
                        (" const", false)
                    }
                } else {
                    // self (by value) → non-const method (consumes)
                    ("", false)
                }
            }
            _ => {
                // No self → static method
                ("", true)
            }
        };

        // Build params list (skip self receiver)
        let params: Vec<String> = method
            .sig
            .inputs
            .iter()
            .filter_map(|arg| match arg {
                syn::FnArg::Receiver(_) => None,
                syn::FnArg::Typed(pat_type) => {
                    let ty = self.map_type(&pat_type.ty);
                    let param_name = match pat_type.pat.as_ref() {
                        syn::Pat::Ident(pi) => pi.ident.to_string(),
                        _ => "_".to_string(),
                    };
                    Some(format!("{} {}", ty, param_name))
                }
            })
            .collect();

        let static_prefix = if is_static { "static " } else { "" };
        self.writeln(&format!(
            "{}{} {}({}){} {{",
            static_prefix,
            return_type,
            name,
            params.join(", "),
            qualifier
        ));
        self.indent += 1;
        self.emit_block(&method.block);
        self.indent -= 1;
        self.writeln("}");
    }

    fn emit_block(&mut self, block: &syn::Block) {
        // Pre-scan: find variables that are reassigned (for reference rebinding detection)
        let reassigned = collect_reassigned_vars(&block.stmts);
        let prev = std::mem::replace(&mut self.reassigned_vars, reassigned);

        let stmts = &block.stmts;
        let len = stmts.len();

        for (i, stmt) in stmts.iter().enumerate() {
            let is_last = i == len - 1;
            self.emit_stmt(stmt, is_last);
        }

        self.reassigned_vars = prev;
    }

    fn emit_stmt(&mut self, stmt: &syn::Stmt, is_tail: bool) {
        match stmt {
            syn::Stmt::Local(local) => self.emit_local(local),
            syn::Stmt::Expr(expr, semi) => {
                // Control flow expressions are emitted as statements directly
                if self.try_emit_control_flow(expr) {
                    return;
                }
                let expr_str = self.emit_expr_to_string(expr);
                if is_tail && semi.is_none() {
                    // Tail expression without semicolon → return
                    self.writeln(&format!("return {};", expr_str));
                } else {
                    self.writeln(&format!("{};", expr_str));
                }
            }
            syn::Stmt::Item(item) => self.emit_item(item),
            syn::Stmt::Macro(_) => {
                self.writeln("// TODO: macro invocation");
            }
        }
    }

    /// Try to emit an expression as a control flow statement.
    /// Returns true if it was handled, false if it should go through emit_expr_to_string.
    fn try_emit_control_flow(&mut self, expr: &syn::Expr) -> bool {
        match expr {
            syn::Expr::If(if_expr) => {
                self.emit_if(if_expr);
                true
            }
            syn::Expr::While(while_expr) => {
                self.emit_while(while_expr);
                true
            }
            syn::Expr::Loop(loop_expr) => {
                self.emit_loop(loop_expr);
                true
            }
            syn::Expr::ForLoop(for_expr) => {
                self.emit_for_loop(for_expr);
                true
            }
            syn::Expr::Block(block_expr) => {
                self.writeln("{");
                self.indent += 1;
                self.emit_block(&block_expr.block);
                self.indent -= 1;
                self.writeln("}");
                true
            }
            syn::Expr::Unsafe(unsafe_expr) => {
                self.writeln("// unsafe");
                self.writeln("{");
                self.indent += 1;
                self.emit_block(&unsafe_expr.block);
                self.indent -= 1;
                self.writeln("}");
                true
            }
            syn::Expr::Match(match_expr) => {
                self.emit_match(match_expr);
                true
            }
            _ => false,
        }
    }

    fn emit_match(&mut self, match_expr: &syn::ExprMatch) {
        let scrutinee = self.emit_expr_to_string(&match_expr.expr);

        // Decide strategy: switch (for literals/wildcards) or std::visit (for variant patterns)
        if self.all_arms_are_literal_or_wild(&match_expr.arms) {
            self.emit_match_as_switch(&scrutinee, &match_expr.arms);
        } else {
            self.emit_match_as_visit(&scrutinee, &match_expr.arms);
        }
    }

    /// Check if all match arms use literal patterns, wildcards, or ident bindings.
    fn all_arms_are_literal_or_wild(&self, arms: &[syn::Arm]) -> bool {
        arms.iter().all(|arm| {
            matches!(
                &arm.pat,
                syn::Pat::Lit(_) | syn::Pat::Wild(_) | syn::Pat::Ident(_)
                    | syn::Pat::Or(_) | syn::Pat::Range(_)
            )
        })
    }

    fn emit_match_as_switch(&mut self, scrutinee: &str, arms: &[syn::Arm]) {
        self.writeln(&format!("switch ({}) {{", scrutinee));
        for arm in arms {
            match &arm.pat {
                syn::Pat::Wild(_) => {
                    self.writeln("default: {");
                }
                syn::Pat::Lit(lit) => {
                    let val = self.emit_lit(&lit.lit);
                    self.writeln(&format!("case {}: {{", val));
                }
                syn::Pat::Or(or_pat) => {
                    // Multiple patterns: `1 | 2 | 3 =>`
                    for (i, case) in or_pat.cases.iter().enumerate() {
                        if let syn::Pat::Lit(lit) = case {
                            let val = self.emit_lit(&lit.lit);
                            if i < or_pat.cases.len() - 1 {
                                self.writeln(&format!("case {}:", val));
                            } else {
                                self.writeln(&format!("case {}: {{", val));
                            }
                        } else if let syn::Pat::Wild(_) = case {
                            self.writeln("default: {");
                        }
                    }
                }
                syn::Pat::Ident(pi) => {
                    // Catch-all binding: `x =>`  acts like default
                    let name = &pi.ident;
                    self.writeln("default: {");
                    self.indent += 1;
                    self.writeln(&format!("auto {} = {};", name, scrutinee));
                    self.indent -= 1;
                }
                syn::Pat::Range(_) => {
                    self.writeln("// TODO: range pattern in switch");
                    self.writeln("default: {");
                }
                _ => {
                    self.writeln("// TODO: unhandled switch pattern");
                    self.writeln("default: {");
                }
            }

            self.indent += 1;

            // Emit guard if present
            if let Some((_, guard)) = &arm.guard {
                let guard_str = self.emit_expr_to_string(guard);
                self.writeln(&format!("if ({}) {{", guard_str));
                self.indent += 1;
                self.emit_arm_body(&arm.body);
                self.indent -= 1;
                self.writeln("}");
            } else {
                self.emit_arm_body(&arm.body);
            }

            self.writeln("break;");
            self.indent -= 1;
            self.writeln("}");
        }
        self.writeln("}");
    }

    fn emit_match_as_visit(&mut self, scrutinee: &str, arms: &[syn::Arm]) {
        // Emit: std::visit(overloaded { [](Type& v) { ... }, ... }, scrutinee);
        self.writeln(&format!("std::visit(overloaded {{"));
        self.indent += 1;

        for arm in arms {
            self.emit_visit_arm(arm);
        }

        self.indent -= 1;
        self.writeln(&format!("}}, {});", scrutinee));
    }

    fn emit_visit_arm(&mut self, arm: &syn::Arm) {
        match &arm.pat {
            syn::Pat::TupleStruct(ts) => {
                // Pattern like `Shape::Circle(r)` → [](const Shape_Circle& _v) { auto r = _v._0; ... }
                let path = self.emit_path_to_string(&ts.path);
                // Convert :: to _ for variant struct name
                let cpp_type = path.replace("::", "_");
                let bindings = self.extract_tuple_struct_bindings(&ts.elems);

                self.write_indent();
                self.output.push_str(&format!("[](const {}& _v) {{", cpp_type));

                if !bindings.is_empty() || arm.guard.is_some() {
                    self.output.push('\n');
                    self.indent += 1;
                    // Emit bindings
                    for (i, name) in bindings.iter().enumerate() {
                        if name != "_" {
                            self.writeln(&format!("const auto& {} = _v._{};", name, i));
                        }
                    }
                    if let Some((_, guard)) = &arm.guard {
                        let guard_str = self.emit_expr_to_string(guard);
                        self.writeln(&format!("if ({}) {{", guard_str));
                        self.indent += 1;
                        self.emit_arm_body(&arm.body);
                        self.indent -= 1;
                        self.writeln("}");
                    } else {
                        self.emit_arm_body(&arm.body);
                    }
                    self.indent -= 1;
                    self.writeln("},");
                } else {
                    let body_str = self.emit_expr_to_string(&arm.body);
                    self.output.push_str(&format!(" {}; }},\n", body_str));
                }
            }
            syn::Pat::Struct(ps) => {
                // Pattern like `Shape::Rect { w, h }` → [](const Shape_Rect& _v) { ... }
                let path = self.emit_path_to_string(&ps.path);
                let cpp_type = path.replace("::", "_");

                self.write_indent();
                self.output.push_str(&format!("[](const {}& _v) {{\n", cpp_type));
                self.indent += 1;

                // Emit field bindings
                for field_pat in &ps.fields {
                    let field_name = field_pat.member.clone();
                    let field_name_str = match &field_name {
                        syn::Member::Named(ident) => ident.to_string(),
                        syn::Member::Unnamed(idx) => format!("_{}", idx.index),
                    };
                    let binding_name = match &*field_pat.pat {
                        syn::Pat::Ident(pi) => pi.ident.to_string(),
                        _ => field_name_str.clone(),
                    };
                    self.writeln(&format!("const auto& {} = _v.{};", binding_name, field_name_str));
                }

                if let Some((_, guard)) = &arm.guard {
                    let guard_str = self.emit_expr_to_string(guard);
                    self.writeln(&format!("if ({}) {{", guard_str));
                    self.indent += 1;
                    self.emit_arm_body(&arm.body);
                    self.indent -= 1;
                    self.writeln("}");
                } else {
                    self.emit_arm_body(&arm.body);
                }

                self.indent -= 1;
                self.writeln("},");
            }
            syn::Pat::Path(pp) => {
                // Unit variant: `Shape::None` → [](const Shape_None&) { ... }
                let path = self.emit_path_to_string(&pp.path);
                let cpp_type = path.replace("::", "_");

                self.write_indent();
                self.output.push_str(&format!("[](const {}&) {{\n", cpp_type));
                self.indent += 1;
                self.emit_arm_body(&arm.body);
                self.indent -= 1;
                self.writeln("},");
            }
            syn::Pat::Wild(_) => {
                // Wildcard: `_ =>` → [](const auto&) { ... }
                self.write_indent();
                self.output.push_str("[](const auto&) {\n");
                self.indent += 1;
                self.emit_arm_body(&arm.body);
                self.indent -= 1;
                self.writeln("},");
            }
            syn::Pat::Ident(pi) => {
                // Catch-all binding: `x =>` → [](const auto& x) { ... }
                let name = &pi.ident;
                self.write_indent();
                self.output.push_str(&format!("[](const auto& {}) {{\n", name));
                self.indent += 1;
                self.emit_arm_body(&arm.body);
                self.indent -= 1;
                self.writeln("},");
            }
            _ => {
                self.writeln("// TODO: unhandled match pattern");
                self.writeln("[](const auto&) {},");
            }
        }
    }

    fn extract_tuple_struct_bindings(
        &self,
        elems: &syn::punctuated::Punctuated<syn::Pat, syn::token::Comma>,
    ) -> Vec<String> {
        elems
            .iter()
            .map(|p| match p {
                syn::Pat::Ident(pi) => pi.ident.to_string(),
                syn::Pat::Wild(_) => "_".to_string(),
                _ => "/* TODO */".to_string(),
            })
            .collect()
    }

    fn emit_arm_body(&mut self, body: &syn::Expr) {
        // If the body is a block, emit its statements
        if let syn::Expr::Block(block) = body {
            self.emit_block(&block.block);
        } else if self.try_emit_control_flow(body) {
            // Control flow handled
        } else {
            let body_str = self.emit_expr_to_string(body);
            self.writeln(&format!("{};", body_str));
        }
    }

    fn emit_if(&mut self, if_expr: &syn::ExprIf) {
        self.emit_if_inner(if_expr, true);
    }

    fn emit_if_inner(&mut self, if_expr: &syn::ExprIf, first: bool) {
        let cond = self.emit_expr_to_string(&if_expr.cond);
        if first {
            self.writeln(&format!("if ({}) {{", cond));
        } else {
            // Continuation of else-if chain — "} else if (...) {" already on current line
            self.output.push_str(&format!("if ({}) {{\n", cond));
        }
        self.indent += 1;
        self.emit_block(&if_expr.then_branch);
        self.indent -= 1;

        if let Some((_, else_branch)) = &if_expr.else_branch {
            match else_branch.as_ref() {
                syn::Expr::If(else_if) => {
                    self.write_indent();
                    self.output.push_str("} else ");
                    self.emit_if_inner(else_if, false);
                    return;
                }
                syn::Expr::Block(block) => {
                    self.writeln("} else {");
                    self.indent += 1;
                    self.emit_block(&block.block);
                    self.indent -= 1;
                }
                _ => {
                    let else_str = self.emit_expr_to_string(else_branch);
                    self.writeln("} else {");
                    self.indent += 1;
                    self.writeln(&format!("{};", else_str));
                    self.indent -= 1;
                }
            }
        }
        self.writeln("}");
    }

    fn emit_while(&mut self, while_expr: &syn::ExprWhile) {
        let cond = self.emit_expr_to_string(&while_expr.cond);
        self.writeln(&format!("while ({}) {{", cond));
        self.indent += 1;
        self.emit_block(&while_expr.body);
        self.indent -= 1;
        self.writeln("}");
    }

    fn emit_loop(&mut self, loop_expr: &syn::ExprLoop) {
        // Check if this loop uses break-with-value.
        // If a loop has `break <expr>`, it's used as a value-producing loop.
        // We emit it as-is, and when used as `let x = loop { ... break val; }`,
        // the break-with-value is handled by emit_expr_to_string emitting `return val`.
        // The enclosing `let x = loop { ... }` should wrap in a lambda —
        // but that's handled at the let-binding level.
        self.writeln("while (true) {");
        self.indent += 1;
        self.emit_block(&loop_expr.body);
        self.indent -= 1;
        self.writeln("}");
    }

    fn emit_for_loop(&mut self, for_expr: &syn::ExprForLoop) {
        let pat = self.emit_pat_to_string(&for_expr.pat);
        let iter = self.emit_expr_to_string(&for_expr.expr);

        // Rust `for x in expr` → C++ `for (auto& x : expr)` or `for (auto x : expr)`
        // Use auto&& to handle both references and values correctly
        self.writeln(&format!("for (auto&& {} : {}) {{", pat, iter));
        self.indent += 1;
        self.emit_block(&for_expr.body);
        self.indent -= 1;
        self.writeln("}");
    }

    fn emit_pat_to_string(&self, pat: &syn::Pat) -> String {
        match pat {
            syn::Pat::Ident(pi) => pi.ident.to_string(),
            syn::Pat::Wild(_) => "_".to_string(),
            syn::Pat::Tuple(pt) => {
                let elems: Vec<String> = pt.elems.iter().map(|p| self.emit_pat_to_string(p)).collect();
                format!("[{}]", elems.join(", "))
            }
            syn::Pat::Reference(pr) => self.emit_pat_to_string(&pr.pat),
            _ => "/* TODO: pattern */".to_string(),
        }
    }

    fn emit_local(&mut self, local: &syn::Local) {
        let pat = &local.pat;

        match pat {
            syn::Pat::Ident(pat_ident) => {
                let name = &pat_ident.ident;
                let is_mut = pat_ident.mutability.is_some();

                let type_str = if let Some(ty) = get_local_type(local) {
                    self.map_type(ty)
                } else {
                    "auto".to_string()
                };

                let qualifier = if is_mut { "" } else { "const " };

                if let Some(init) = &local.init {
                    // Special case: `let x = loop { ... break val; }` → lambda wrapper
                    if let syn::Expr::Loop(loop_expr) = init.expr.as_ref() {
                        self.writeln(&format!(
                            "{}{} {} = [&]() {{",
                            qualifier, type_str, name
                        ));
                        self.indent += 1;
                        self.writeln("while (true) {");
                        self.indent += 1;
                        self.emit_block(&loop_expr.body);
                        self.indent -= 1;
                        self.writeln("}");
                        self.indent -= 1;
                        self.writeln("}();");
                    } else if self.is_ref_init(&init.expr) {
                        let inner = self.extract_ref_inner(&init.expr);
                        if is_mut && self.reassigned_vars.contains(&name.to_string()) {
                            // Reference rebinding detected: `let mut r = &x; ... r = &y;`
                            // Emit as pointer instead of reference
                            let ptr_type = self.map_ref_as_pointer_type(local, &init.expr);
                            self.writeln(&format!(
                                "{} {} = &{};",
                                ptr_type, name, inner
                            ));
                        } else {
                            // No rebinding: `let r = &x` → `const auto& r = x`
                            //               `let r = &mut x` → `auto& r = x`
                            let is_mut_ref = matches!(&*init.expr, syn::Expr::Reference(r) if r.mutability.is_some());
                            let ref_qualifier = if is_mut_ref { "" } else { "const " };
                            let ref_type = self.map_ref_as_ref_type(local, &init.expr);
                            self.writeln(&format!(
                                "{}{} {} = {};",
                                ref_qualifier, ref_type, name, inner
                            ));
                        }
                    } else {
                        // For `let y = x` where x is a local variable → insert std::move
                        let expr_str = self.emit_expr_maybe_move(&init.expr);
                        self.writeln(&format!(
                            "{}{} {} = {};",
                            qualifier, type_str, name, expr_str
                        ));
                    }
                } else {
                    self.writeln(&format!("{}{} {};", qualifier, type_str, name));
                }
            }
            syn::Pat::Tuple(tuple) => {
                // let (a, b) = expr; → auto [a, b] = expr;
                let names: Vec<String> = tuple
                    .elems
                    .iter()
                    .map(|p| self.emit_pat_to_string(p))
                    .collect();
                if let Some(init) = &local.init {
                    let expr_str = self.emit_expr_to_string(&init.expr);
                    self.writeln(&format!("auto [{}] = {};", names.join(", "), expr_str));
                }
            }
            syn::Pat::Type(pat_type) => {
                // let x: Type = expr;
                // The type annotation is on the pattern, inner pat has the name
                if let syn::Pat::Ident(pi) = pat_type.pat.as_ref() {
                    let name = &pi.ident;
                    let is_mut = pi.mutability.is_some();
                    let ty = self.map_type(&pat_type.ty);
                    let qualifier = if is_mut { "" } else { "const " };
                    if let Some(init) = &local.init {
                        let expr_str = self.emit_expr_to_string(&init.expr);
                        self.writeln(&format!("{}{} {} = {};", qualifier, ty, name, expr_str));
                    } else {
                        self.writeln(&format!("{}{} {};", qualifier, ty, name));
                    }
                } else {
                    self.writeln("// TODO: complex typed pattern binding");
                }
            }
            _ => {
                self.writeln("// TODO: complex pattern binding");
            }
        }
    }

    fn emit_expr_to_string(&self, expr: &syn::Expr) -> String {
        match expr {
            syn::Expr::Lit(lit) => self.emit_lit(&lit.lit),
            syn::Expr::Path(path) => self.emit_path_to_string(&path.path),
            syn::Expr::Binary(bin) => {
                let left = self.emit_expr_to_string(&bin.left);
                let op = self.emit_binop(&bin.op);
                let right = self.emit_expr_to_string(&bin.right);
                format!("{} {} {}", left, op, right)
            }
            syn::Expr::Unary(un) => {
                let operand = self.emit_expr_to_string(&un.expr);
                match un.op {
                    syn::UnOp::Neg(_) => format!("-{}", operand),
                    syn::UnOp::Not(_) => format!("!{}", operand),
                    syn::UnOp::Deref(_) => format!("*{}", operand),
                    _ => format!("/* unknown unary */ {}", operand),
                }
            }
            syn::Expr::Reference(r) => {
                let inner = self.emit_expr_to_string(&r.expr);
                format!("&{}", inner)
            }
            syn::Expr::Call(call) => {
                let func = self.emit_expr_to_string(&call.func);
                let args: Vec<String> = call
                    .args
                    .iter()
                    .map(|a| self.emit_expr_maybe_move(a))
                    .collect();
                format!("{}({})", func, args.join(", "))
            }
            syn::Expr::MethodCall(mc) => {
                let method = &mc.method;
                let args: Vec<String> = mc
                    .args
                    .iter()
                    .map(|a| self.emit_expr_maybe_move(a))
                    .collect();
                // Check if receiver is `self` — in C++ methods, call directly
                let is_self = matches!(mc.receiver.as_ref(), syn::Expr::Path(p)
                    if p.path.segments.len() == 1 && p.path.segments[0].ident == "self");
                if is_self {
                    format!("{}({})", method, args.join(", "))
                } else {
                    let receiver = self.emit_expr_to_string(&mc.receiver);
                    format!("{}.{}({})", receiver, method, args.join(", "))
                }
            }
            syn::Expr::Field(f) => {
                // Check if base is `self` — in C++ methods, fields are directly accessible
                let is_self = matches!(f.base.as_ref(), syn::Expr::Path(p)
                    if p.path.segments.len() == 1 && p.path.segments[0].ident == "self");
                if is_self {
                    match &f.member {
                        syn::Member::Named(ident) => ident.to_string(),
                        syn::Member::Unnamed(idx) => format!("_{}", idx.index),
                    }
                } else {
                    let base = self.emit_expr_to_string(&f.base);
                    match &f.member {
                        syn::Member::Named(ident) => format!("{}.{}", base, ident),
                        syn::Member::Unnamed(idx) => format!("{}._{}", base, idx.index),
                    }
                }
            }
            syn::Expr::If(if_expr) => {
                // If used as an expression (e.g., `let x = if c { 1 } else { 2 };`)
                // → C++ ternary when simple
                if let Some((_, else_branch)) = &if_expr.else_branch {
                    let cond = self.emit_expr_to_string(&if_expr.cond);
                    if let (Some(then_val), Some(else_val)) =
                        (self.block_single_expr(&if_expr.then_branch), self.expr_single_value(else_branch))
                    {
                        return format!("({} ? {} : {})", cond, then_val, else_val);
                    }
                }
                format!("/* TODO: if-expression */")
            }
            syn::Expr::Break(brk) => {
                match &brk.expr {
                    Some(val) => {
                        let v = self.emit_expr_to_string(val);
                        format!("return {}", v)  // break-with-value inside lambda wrapper
                    }
                    None => "break".to_string(),
                }
            }
            syn::Expr::Continue(_) => "continue".to_string(),
            syn::Expr::Range(range) => {
                // Rust range `a..b` → we need a range helper; for now emit for use in for-loops
                let start = range.start.as_ref().map(|e| self.emit_expr_to_string(e)).unwrap_or_default();
                let end = range.end.as_ref().map(|e| self.emit_expr_to_string(e)).unwrap_or_default();
                format!("rusty::range({}, {})", start, end)
            }
            syn::Expr::Closure(closure) => {
                let params: Vec<String> = closure.inputs.iter().map(|p| {
                    self.emit_pat_to_string(p)
                }).collect();
                let body = self.emit_expr_to_string(&closure.body);
                format!("[&](auto {}) {{ return {}; }}", params.join(", auto "), body)
            }
            syn::Expr::Return(ret) => match &ret.expr {
                Some(e) => {
                    let val = self.emit_expr_to_string(e);
                    format!("return {}", val)
                }
                None => "return".to_string(),
            },
            syn::Expr::Assign(a) => {
                let left = self.emit_expr_to_string(&a.left);
                let right = self.emit_expr_to_string(&a.right);
                format!("{} = {}", left, right)
            }
            syn::Expr::Struct(s) => {
                let name = self.emit_path_to_string(&s.path);
                let fields: Vec<String> = s
                    .fields
                    .iter()
                    .map(|f| {
                        let val = self.emit_expr_to_string(&f.expr);
                        let member_name = match &f.member {
                            syn::Member::Named(ident) => ident.to_string(),
                            syn::Member::Unnamed(idx) => format!("_{}", idx.index),
                        };
                        format!(".{} = {}", member_name, val)
                    })
                    .collect();
                format!("{}{{{}}}", name, fields.join(", "))
            }
            syn::Expr::Paren(p) => {
                let inner = self.emit_expr_to_string(&p.expr);
                format!("({})", inner)
            }
            syn::Expr::Cast(c) => {
                let expr = self.emit_expr_to_string(&c.expr);
                let ty = self.map_type(&c.ty);
                format!("static_cast<{}>({})", ty, expr)
            }
            syn::Expr::Index(idx) => {
                let base = self.emit_expr_to_string(&idx.expr);
                let index = self.emit_expr_to_string(&idx.index);
                format!("{}[{}]", base, index)
            }
            syn::Expr::Tuple(tup) => {
                let elems: Vec<String> = tup
                    .elems
                    .iter()
                    .map(|e| self.emit_expr_to_string(e))
                    .collect();
                format!("std::make_tuple({})", elems.join(", "))
            }
            _ => format!("/* TODO: expr */"),
        }
    }

    fn emit_lit(&self, lit: &syn::Lit) -> String {
        match lit {
            syn::Lit::Int(i) => i.base10_digits().to_string(),
            syn::Lit::Float(f) => f.base10_digits().to_string(),
            syn::Lit::Bool(b) => if b.value { "true" } else { "false" }.to_string(),
            syn::Lit::Str(s) => format!("\"{}\"", s.value()),
            syn::Lit::Char(c) => format!("U'{}'", c.value()),
            syn::Lit::Byte(b) => format!("static_cast<uint8_t>({})", b.value()),
            _ => "/* TODO: literal */".to_string(),
        }
    }

    fn emit_binop(&self, op: &syn::BinOp) -> &'static str {
        match op {
            syn::BinOp::Add(_) => "+",
            syn::BinOp::Sub(_) => "-",
            syn::BinOp::Mul(_) => "*",
            syn::BinOp::Div(_) => "/",
            syn::BinOp::Rem(_) => "%",
            syn::BinOp::And(_) => "&&",
            syn::BinOp::Or(_) => "||",
            syn::BinOp::BitXor(_) => "^",
            syn::BinOp::BitAnd(_) => "&",
            syn::BinOp::BitOr(_) => "|",
            syn::BinOp::Shl(_) => "<<",
            syn::BinOp::Shr(_) => ">>",
            syn::BinOp::Eq(_) => "==",
            syn::BinOp::Lt(_) => "<",
            syn::BinOp::Le(_) => "<=",
            syn::BinOp::Ne(_) => "!=",
            syn::BinOp::Ge(_) => ">=",
            syn::BinOp::Gt(_) => ">",
            syn::BinOp::AddAssign(_) => "+=",
            syn::BinOp::SubAssign(_) => "-=",
            syn::BinOp::MulAssign(_) => "*=",
            syn::BinOp::DivAssign(_) => "/=",
            syn::BinOp::RemAssign(_) => "%=",
            syn::BinOp::BitXorAssign(_) => "^=",
            syn::BinOp::BitAndAssign(_) => "&=",
            syn::BinOp::BitOrAssign(_) => "|=",
            syn::BinOp::ShlAssign(_) => "<<=",
            syn::BinOp::ShrAssign(_) => ">>=",
            _ => "/* unknown op */",
        }
    }

    fn emit_path_to_string(&self, path: &syn::Path) -> String {
        let segments: Vec<String> = path.segments.iter().map(|s| s.ident.to_string()).collect();
        let joined = segments.join("::");

        // Resolve `Self` to current struct name
        if segments.len() == 1 && segments[0] == "Self" {
            if let Some(ref struct_name) = self.current_struct {
                return struct_name.clone();
            }
        }

        // Resolve `self` to `(*this)` — for field access, `self.x` becomes `this->x`
        if segments.len() == 1 && segments[0] == "self" {
            return "(*this)".to_string();
        }

        // Try mapping as a function/method path (e.g., Box::new → rusty::Box::make)
        if let Some(cpp_fn) = types::map_function_path(&joined) {
            return cpp_fn.to_string();
        }

        // Try mapping as a standard type
        if let Some((cpp_type, _)) = types::map_std_type(&joined) {
            return cpp_type.to_string();
        }

        // Try as primitive
        if segments.len() == 1 {
            if let Some(cpp_prim) = types::map_primitive_type(&segments[0]) {
                return cpp_prim.to_string();
            }
        }

        // Escape C++ keywords in the last segment (e.g., Point::new → Point::new_)
        if segments.len() > 1 {
            let mut escaped = segments.clone();
            if let Some(last) = escaped.last_mut() {
                *last = escape_cpp_keyword(last);
            }
            return escaped.join("::");
        }

        // Single segment — escape if keyword
        escape_cpp_keyword(&joined)
    }

    fn map_type(&self, ty: &syn::Type) -> String {
        match ty {
            syn::Type::Path(tp) => {
                let path_str = self.emit_path_to_string(&tp.path);

                // Check if the last segment has generic arguments
                if let Some(last_seg) = tp.path.segments.last() {
                    if let syn::PathArguments::AngleBracketed(args) = &last_seg.arguments {
                        let type_args: Vec<String> = args
                            .args
                            .iter()
                            .filter_map(|arg| {
                                if let syn::GenericArgument::Type(t) = arg {
                                    Some(self.map_type(t))
                                } else {
                                    None
                                }
                            })
                            .collect();

                        if !type_args.is_empty() {
                            // Re-map the base without the args we already processed
                            let base = {
                                let segs: Vec<String> = tp
                                    .path
                                    .segments
                                    .iter()
                                    .map(|s| s.ident.to_string())
                                    .collect();
                                let joined = segs.join("::");
                                if let Some((cpp, _)) = types::map_std_type(&joined) {
                                    cpp.to_string()
                                } else if segs.len() == 1 {
                                    types::map_primitive_type(&segs[0])
                                        .map(|s| s.to_string())
                                        .unwrap_or(joined)
                                } else {
                                    joined
                                }
                            };
                            return format!("{}<{}>", base, type_args.join(", "));
                        }
                    }
                }

                path_str
            }
            syn::Type::Reference(r) => {
                // Special case: &str → std::string_view (not const std::string_view&)
                if let syn::Type::Path(tp) = r.elem.as_ref() {
                    if tp.path.segments.len() == 1 && tp.path.segments[0].ident == "str" {
                        return "std::string_view".to_string();
                    }
                }
                let inner = self.map_type(&r.elem);
                if r.mutability.is_some() {
                    format!("{}&", inner)
                } else {
                    format!("const {}&", inner)
                }
            }
            syn::Type::Ptr(p) => {
                let inner = self.map_type(&p.elem);
                if p.mutability.is_some() {
                    format!("{}*", inner)
                } else {
                    format!("const {}*", inner)
                }
            }
            syn::Type::Tuple(t) => {
                if t.elems.is_empty() {
                    "void".to_string()
                } else {
                    let elems: Vec<String> = t.elems.iter().map(|e| self.map_type(e)).collect();
                    format!("std::tuple<{}>", elems.join(", "))
                }
            }
            syn::Type::Array(a) => {
                let elem = self.map_type(&a.elem);
                let len = self.emit_expr_to_string(&a.len);
                format!("std::array<{}, {}>", elem, len)
            }
            syn::Type::Slice(s) => {
                let elem = self.map_type(&s.elem);
                format!("std::span<const {}>", elem)
            }
            syn::Type::Never(_) => "[[noreturn]] void".to_string(),
            syn::Type::Infer(_) => "auto".to_string(),
            _ => "/* TODO: type */".to_string(),
        }
    }

    /// Emit an expression, wrapping local variable paths in std::move().
    /// In Rust, passing a non-Copy variable by value moves it. In C++, we need
    /// explicit std::move() to get move semantics. For Copy types, std::move()
    /// is a harmless no-op (the copy still happens).
    ///
    /// We wrap in std::move when:
    /// - The expression is a simple variable path (single ident)
    /// - It's not `self`, `true`, `false`, `Self`, or an ALL_CAPS constant
    /// - It's not a reference expression (&x)
    ///
    /// We do NOT wrap:
    /// - Literals (1, "hello", true)
    /// - Reference expressions (&x, &mut x) — these borrow, not move
    /// - Complex expressions (a + b, foo()) — these produce temporaries
    /// - Type paths / constants (ALL_CAPS names)
    fn emit_expr_maybe_move(&self, expr: &syn::Expr) -> String {
        if self.should_insert_move(expr) {
            let inner = self.emit_expr_to_string(expr);
            format!("std::move({})", inner)
        } else {
            self.emit_expr_to_string(expr)
        }
    }

    /// Determine whether an expression represents a local variable that should
    /// be wrapped in std::move() when used by value.
    fn should_insert_move(&self, expr: &syn::Expr) -> bool {
        match expr {
            syn::Expr::Path(path) => {
                // Only single-segment paths (local variables)
                if path.path.segments.len() != 1 {
                    return false;
                }
                let name = path.path.segments[0].ident.to_string();

                // Skip keywords and special names
                if matches!(
                    name.as_str(),
                    "self" | "Self" | "true" | "false" | "None" | "Some" | "Ok" | "Err"
                ) {
                    return false;
                }

                // Skip ALL_CAPS names (likely constants)
                if name.chars().all(|c| c.is_uppercase() || c == '_') && name.len() > 1 {
                    return false;
                }

                // Skip names that start with uppercase (likely type names or enum variants)
                if name.starts_with(|c: char| c.is_uppercase()) {
                    return false;
                }

                true
            }
            _ => false,
        }
    }

    /// Check if an initializer expression is a reference (`&expr` or `&mut expr`).
    fn is_ref_init(&self, expr: &syn::Expr) -> bool {
        matches!(expr, syn::Expr::Reference(_))
    }

    /// Extract the inner expression from a reference expression, as a string.
    fn extract_ref_inner(&self, expr: &syn::Expr) -> String {
        if let syn::Expr::Reference(r) = expr {
            self.emit_expr_to_string(&r.expr)
        } else {
            self.emit_expr_to_string(expr)
        }
    }

    /// For a reference binding that will become a pointer, determine the pointer type.
    /// `let mut r = &x` where x: T → `const T*`
    /// `let mut r = &mut x` where x: T → `T*`
    /// `let mut r: &T = &x` → `const T*`
    /// `let mut r: &mut T = &mut x` → `T*`
    fn map_ref_as_pointer_type(&self, local: &syn::Local, init_expr: &syn::Expr) -> String {
        // If there's a type annotation, use it
        if let Some(ty) = get_local_type(local) {
            if let syn::Type::Reference(r) = ty {
                let inner = self.map_type(&r.elem);
                return if r.mutability.is_some() {
                    format!("{}*", inner)
                } else {
                    format!("const {}*", inner)
                };
            }
        }
        // Infer from the init expression
        if let syn::Expr::Reference(r) = init_expr {
            if r.mutability.is_some() {
                "auto*".to_string()
            } else {
                "const auto*".to_string()
            }
        } else {
            "auto*".to_string()
        }
    }

    /// For a non-rebound reference binding, determine the reference type.
    /// `let r = &x` → `auto&` (the const qualifier is added separately)
    /// `let r = &mut x` → `auto&` (mutable, no const)
    fn map_ref_as_ref_type(&self, local: &syn::Local, init_expr: &syn::Expr) -> String {
        if let Some(ty) = get_local_type(local) {
            if let syn::Type::Reference(r) = ty {
                let inner = self.map_type(&r.elem);
                return if r.mutability.is_some() {
                    format!("{}&", inner)
                } else {
                    format!("const {}&", inner)
                };
            }
        }
        if let syn::Expr::Reference(r) = init_expr {
            if r.mutability.is_some() {
                "auto&".to_string()
            } else {
                "auto&".to_string()
            }
        } else {
            "auto&".to_string()
        }
    }

    /// If a block contains exactly one expression (tail expr), return its string form.
    fn block_single_expr(&self, block: &syn::Block) -> Option<String> {
        if block.stmts.len() == 1 {
            if let syn::Stmt::Expr(expr, None) = &block.stmts[0] {
                return Some(self.emit_expr_to_string(expr));
            }
        }
        None
    }

    /// Extract the single value from an else branch expression.
    fn expr_single_value(&self, expr: &syn::Expr) -> Option<String> {
        match expr {
            syn::Expr::Block(block) => self.block_single_expr(&block.block),
            _ => Some(self.emit_expr_to_string(expr)),
        }
    }

    fn map_return_type(&self, output: &syn::ReturnType) -> String {
        match output {
            syn::ReturnType::Default => "void".to_string(),
            syn::ReturnType::Type(_, ty) => self.map_type(ty),
        }
    }

    fn map_fn_params(&self, inputs: &syn::punctuated::Punctuated<syn::FnArg, syn::token::Comma>) -> String {
        let params: Vec<String> = inputs
            .iter()
            .map(|arg| match arg {
                syn::FnArg::Typed(pat_type) => {
                    let ty = self.map_type(&pat_type.ty);
                    let name = match pat_type.pat.as_ref() {
                        syn::Pat::Ident(pi) => pi.ident.to_string(),
                        _ => "_".to_string(),
                    };
                    format!("{} {}", ty, name)
                }
                syn::FnArg::Receiver(_) => "/* self */".to_string(),
            })
            .collect();
        params.join(", ")
    }
}

/// Escape C++ reserved keywords by appending an underscore.
fn escape_cpp_keyword(name: &str) -> String {
    match name {
        "new" | "delete" | "class" | "template" | "virtual" | "override" | "final"
        | "operator" | "friend" | "namespace" | "using" | "throw" | "catch" | "try"
        | "public" | "private" | "protected" | "mutable" | "volatile" | "register"
        | "inline" | "explicit" | "export" | "typedef" | "typename" | "decltype"
        | "constexpr" | "nullptr" | "alignof" | "alignas" | "thread_local"
        | "static_assert" | "noexcept" | "consteval" | "constinit" | "co_await"
        | "co_return" | "co_yield" | "requires" | "concept" | "import" | "module" => {
            format!("{}_", name)
        }
        _ => name.to_string(),
    }
}

/// Scan a list of statements and collect the names of variables that are reassigned.
/// This is used for reference rebinding detection: `let mut r = &x; r = &y;`
/// means `r` should be emitted as a pointer, not a reference.
fn collect_reassigned_vars(stmts: &[syn::Stmt]) -> std::collections::HashSet<String> {
    let mut result = std::collections::HashSet::new();
    for stmt in stmts {
        collect_assignments_in_stmt(stmt, &mut result);
    }
    result
}

/// Recursively collect assignment targets from a statement.
fn collect_assignments_in_stmt(stmt: &syn::Stmt, result: &mut std::collections::HashSet<String>) {
    match stmt {
        syn::Stmt::Expr(expr, _) => collect_assignments_in_expr(expr, result),
        _ => {}
    }
}

/// Recursively collect assignment targets from an expression.
fn collect_assignments_in_expr(expr: &syn::Expr, result: &mut std::collections::HashSet<String>) {
    match expr {
        syn::Expr::Assign(assign) => {
            // `r = ...` → r is reassigned
            if let syn::Expr::Path(path) = assign.left.as_ref() {
                if path.path.segments.len() == 1 {
                    result.insert(path.path.segments[0].ident.to_string());
                }
            }
        }
        syn::Expr::Block(block) => {
            for s in &block.block.stmts {
                collect_assignments_in_stmt(s, result);
            }
        }
        syn::Expr::If(if_expr) => {
            for s in &if_expr.then_branch.stmts {
                collect_assignments_in_stmt(s, result);
            }
            if let Some((_, else_branch)) = &if_expr.else_branch {
                collect_assignments_in_expr(else_branch, result);
            }
        }
        syn::Expr::While(w) => {
            for s in &w.body.stmts {
                collect_assignments_in_stmt(s, result);
            }
        }
        syn::Expr::Loop(l) => {
            for s in &l.body.stmts {
                collect_assignments_in_stmt(s, result);
            }
        }
        syn::Expr::ForLoop(f) => {
            for s in &f.body.stmts {
                collect_assignments_in_stmt(s, result);
            }
        }
        syn::Expr::Unsafe(u) => {
            for s in &u.block.stmts {
                collect_assignments_in_stmt(s, result);
            }
        }
        _ => {}
    }
}

/// Extract the type annotation from a local variable binding, if present.
fn get_local_type(local: &syn::Local) -> Option<&syn::Type> {
    match &local.pat {
        syn::Pat::Type(pt) => Some(&pt.ty),
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn transpile_str(rust_code: &str) -> String {
        let file: syn::File = syn::parse_str(rust_code).unwrap();
        let mut cg = CodeGen::new();
        cg.emit_file(&file);
        cg.into_output()
    }

    #[test]
    fn test_simple_function() {
        let out = transpile_str("fn add(a: i32, b: i32) -> i32 { a + b }");
        assert!(out.contains("int32_t add(int32_t a, int32_t b)"));
        assert!(out.contains("return a + b;"));
    }

    #[test]
    fn test_void_function() {
        let out = transpile_str("fn noop() {}");
        assert!(out.contains("void noop()"));
    }

    #[test]
    fn test_struct() {
        let out = transpile_str("struct Point { x: f64, y: f64 }");
        assert!(out.contains("struct Point {"));
        assert!(out.contains("double x;"));
        assert!(out.contains("double y;"));
    }

    #[test]
    fn test_const() {
        let out = transpile_str("const MAX: i32 = 100;");
        assert!(out.contains("constexpr int32_t MAX = 100;"));
    }

    #[test]
    fn test_c_like_enum() {
        let out = transpile_str("enum Color { Red, Green, Blue }");
        assert!(out.contains("enum class Color {"));
        assert!(out.contains("Red"));
        assert!(out.contains("Green"));
        assert!(out.contains("Blue"));
    }

    #[test]
    fn test_enum_with_data() {
        let out = transpile_str(
            "enum Shape { Circle(f64), Rect { w: f64, h: f64 }, None }",
        );
        assert!(out.contains("struct Shape_Circle {"));
        assert!(out.contains("double _0;"));
        assert!(out.contains("struct Shape_Rect {"));
        assert!(out.contains("double w;"));
        assert!(out.contains("struct Shape_None {}"));
        assert!(out.contains("using Shape = std::variant<"));
    }

    #[test]
    fn test_type_alias() {
        let out = transpile_str("type Num = i32;");
        assert!(out.contains("using Num = int32_t;"));
    }

    #[test]
    fn test_let_binding_immutable() {
        let out = transpile_str("fn f() { let x = 5; }");
        assert!(out.contains("const auto x = 5;"));
    }

    #[test]
    fn test_let_binding_mutable() {
        let out = transpile_str("fn f() { let mut x = 5; }");
        assert!(out.contains("auto x = 5;"));
    }

    #[test]
    fn test_std_type_mapping() {
        let out = transpile_str("fn f(v: Vec<i32>) {}");
        assert!(out.contains("rusty::Vec<int32_t>"));
    }

    #[test]
    fn test_reference_types() {
        let out = transpile_str("fn f(a: &i32, b: &mut i32) {}");
        assert!(out.contains("const int32_t&"));
        assert!(out.contains("int32_t&"));
    }

    #[test]
    fn test_option_type() {
        let out = transpile_str("fn f() -> Option<i32> { 42 }");
        assert!(out.contains("rusty::Option<int32_t>"));
    }

    #[test]
    fn test_tuple_return() {
        let out = transpile_str("fn f() -> (i32, f64) { (1, 2.0) }");
        assert!(out.contains("std::tuple<int32_t, double>"));
    }

    #[test]
    fn test_array_type() {
        let out = transpile_str("fn f(a: [i32; 5]) {}");
        assert!(out.contains("std::array<int32_t, 5>"));
    }

    #[test]
    fn test_unit_return_is_void() {
        let out = transpile_str("fn f() -> () {}");
        assert!(out.contains("void f()"));
    }

    #[test]
    fn test_binary_operators() {
        let out = transpile_str("fn f() -> i32 { 1 + 2 * 3 }");
        assert!(out.contains("return 1 + 2 * 3;"));
    }

    #[test]
    fn test_static_var() {
        let out = transpile_str("static COUNT: i32 = 0;");
        assert!(out.contains("static int32_t COUNT = 0;"));
    }

    #[test]
    fn test_cast() {
        let out = transpile_str("fn f() { let x = 5 as f64; }");
        assert!(out.contains("static_cast<double>(5)"));
    }

    #[test]
    fn test_string_literal() {
        let out = transpile_str(r#"fn f() { let s = "hello"; }"#);
        assert!(out.contains("\"hello\""));
    }

    #[test]
    fn test_bool_literal() {
        let out = transpile_str("fn f() -> bool { true }");
        assert!(out.contains("return true;"));
    }

    #[test]
    fn test_method_call() {
        let out = transpile_str("fn f() { v.push(1); }");
        assert!(out.contains("v.push(1);"));
    }

    #[test]
    fn test_field_access() {
        let out = transpile_str("fn f() -> f64 { p.x }");
        assert!(out.contains("return p.x;"));
    }

    #[test]
    fn test_index_expr() {
        let out = transpile_str("fn f() { let x = arr[0]; }");
        assert!(out.contains("arr[0]"));
    }

    #[test]
    fn test_struct_literal() {
        let out = transpile_str("fn f() -> Point { Point { x: 1.0, y: 2.0 } }");
        assert!(out.contains("Point{"));
        assert!(out.contains(".x = 1.0"));
        assert!(out.contains(".y = 2.0"));
    }

    #[test]
    fn test_result_type() {
        let out = transpile_str("fn f() -> Result<i32, String> { Ok(1) }");
        assert!(out.contains("rusty::Result<int32_t, rusty::String>"));
    }

    #[test]
    fn test_box_type() {
        let out = transpile_str("fn f(b: Box<i32>) {}");
        assert!(out.contains("rusty::Box<int32_t>"));
    }

    #[test]
    fn test_hashmap_type() {
        let out = transpile_str("fn f(m: HashMap<String, i32>) {}");
        assert!(out.contains("rusty::HashMap<rusty::String, int32_t>"));
    }

    // ── Control flow tests ──────────────────────────────────────

    #[test]
    fn test_if_simple() {
        let out = transpile_str("fn f(x: i32) { if x > 0 { x; } }");
        assert!(out.contains("if (x > 0) {"));
        assert!(out.contains("x;"));
        assert!(out.contains("}"));
    }

    #[test]
    fn test_if_else() {
        let out = transpile_str("fn f(x: i32) { if x > 0 { x; } else { 0; } }");
        assert!(out.contains("if (x > 0) {"));
        assert!(out.contains("} else {"));
    }

    #[test]
    fn test_if_else_if() {
        let out = transpile_str(
            "fn f(x: i32) { if x > 0 { 1; } else if x < 0 { 2; } else { 0; } }",
        );
        assert!(out.contains("if (x > 0) {"));
        assert!(out.contains("} else if (x < 0) {"));
        assert!(out.contains("} else {"));
    }

    #[test]
    fn test_if_tail_expr_returns() {
        // When if/else is the tail expression of a function, each branch gets `return`
        let out = transpile_str("fn f(c: bool) -> i32 { if c { 1 } else { 0 } }");
        assert!(out.contains("if (c) {"));
        assert!(out.contains("return 1;"));
        assert!(out.contains("return 0;"));
    }

    #[test]
    fn test_if_expr_as_ternary() {
        // When if/else is used in a let binding with simple branches → ternary
        let out = transpile_str("fn f(c: bool) { let x = if c { 1 } else { 0 }; }");
        assert!(out.contains("(c ? 1 : 0)"));
    }

    #[test]
    fn test_while_loop() {
        let out = transpile_str("fn f() { let mut x = 10; while x > 0 { x = x - 1; } }");
        assert!(out.contains("while (x > 0) {"));
    }

    #[test]
    fn test_infinite_loop() {
        let out = transpile_str("fn f() { loop { break; } }");
        assert!(out.contains("while (true) {"));
        assert!(out.contains("break;"));
    }

    #[test]
    fn test_for_in_range() {
        let out = transpile_str("fn f() { for i in 0..10 { i; } }");
        assert!(out.contains("for (auto&& i : rusty::range(0, 10)) {"));
    }

    #[test]
    fn test_for_in_variable() {
        let out = transpile_str("fn f() { for x in items { x; } }");
        assert!(out.contains("for (auto&& x : items) {"));
    }

    #[test]
    fn test_break_continue() {
        let out = transpile_str("fn f() { loop { if true { break; } continue; } }");
        assert!(out.contains("break;"));
        assert!(out.contains("continue;"));
    }

    #[test]
    fn test_loop_break_with_value() {
        let out = transpile_str(
            "fn f() { let result = loop { if true { break 42; } }; }",
        );
        assert!(out.contains("[&]()"));
        assert!(out.contains("while (true)"));
        assert!(out.contains("return 42;"));
        assert!(out.contains("}();"));
    }

    #[test]
    fn test_nested_if_in_loop() {
        let out = transpile_str(
            "fn f() { while true { if true { break; } else { continue; } } }",
        );
        assert!(out.contains("while (true) {"));
        assert!(out.contains("if (true) {"));
        assert!(out.contains("break;"));
        assert!(out.contains("} else {"));
        assert!(out.contains("continue;"));
    }

    #[test]
    fn test_nested_loops() {
        let out = transpile_str(
            "fn f() { for i in 0..5 { for j in 0..5 { i; } } }",
        );
        assert!(out.contains("for (auto&& i : rusty::range(0, 5)) {"));
        assert!(out.contains("for (auto&& j : rusty::range(0, 5)) {"));
    }

    #[test]
    fn test_if_with_let_binding() {
        let out = transpile_str("fn f() { if true { let x = 1; x; } }");
        assert!(out.contains("if (true) {"));
        assert!(out.contains("const auto x = 1;"));
    }

    #[test]
    fn test_closure_basic() {
        let out = transpile_str("fn f() { let add = |a, b| a + b; }");
        assert!(out.contains("[&]"));
        assert!(out.contains("return a + b;"));
    }

    // ── Impl block and method tests ─────────────────────────────

    #[test]
    fn test_impl_block_merged_into_struct() {
        let out = transpile_str(
            r#"
            struct Foo { x: i32 }
            impl Foo {
                fn get(&self) -> i32 { self.x }
            }
        "#,
        );
        assert!(out.contains("struct Foo {"));
        assert!(out.contains("int32_t x;"));
        assert!(out.contains("int32_t get() const {"));
        assert!(out.contains("return x;"));
        // Impl block should NOT appear separately
        assert!(!out.contains("// TODO: impl block"));
    }

    #[test]
    fn test_method_receivers() {
        let out = transpile_str(
            r#"
            struct S { v: i32 }
            impl S {
                fn by_ref(&self) {}
                fn by_mut_ref(&mut self) {}
                fn by_value(self) {}
                fn associated() {}
            }
        "#,
        );
        assert!(out.contains("void by_ref() const {"));
        assert!(out.contains("void by_mut_ref() {"));
        assert!(out.contains("void by_value() {"));
        assert!(out.contains("static void associated() {"));
    }

    #[test]
    fn test_multiple_impl_blocks_merged() {
        let out = transpile_str(
            r#"
            struct P { x: f64 }
            impl P { fn a(&self) -> f64 { self.x } }
            impl P { fn b(&self) -> f64 { self.x } }
        "#,
        );
        assert!(out.contains("double a() const {"));
        assert!(out.contains("double b() const {"));
        // Both should be inside the struct
        let struct_pos = out.find("struct P {").unwrap();
        let close_pos = out[struct_pos..].find("};").unwrap() + struct_pos;
        let a_pos = out.find("double a()").unwrap();
        let b_pos = out.find("double b()").unwrap();
        assert!(a_pos > struct_pos && a_pos < close_pos);
        assert!(b_pos > struct_pos && b_pos < close_pos);
    }

    #[test]
    fn test_self_field_access() {
        let out = transpile_str(
            r#"
            struct S { val: i32 }
            impl S {
                fn get(&self) -> i32 { self.val }
                fn set(&mut self, v: i32) { self.val = v; }
            }
        "#,
        );
        // self.val → val (direct field access in C++ methods)
        assert!(out.contains("return val;"));
        assert!(out.contains("val = v;"));
    }

    #[test]
    fn test_self_type_resolved() {
        let out = transpile_str(
            r#"
            struct Foo { x: i32 }
            impl Foo {
                fn make() -> Self { Foo { x: 0 } }
            }
        "#,
        );
        // Self → Foo
        assert!(out.contains("static Foo make()"));
    }

    #[test]
    fn test_cpp_keyword_escaping() {
        let out = transpile_str(
            r#"
            struct Widget {}
            impl Widget {
                fn new() -> Self { Widget {} }
                fn delete(&mut self) {}
            }
        "#,
        );
        // new → new_, delete → delete_
        assert!(out.contains("static Widget new_()"));
        assert!(out.contains("void delete_()"));
    }

    #[test]
    fn test_keyword_in_call() {
        let out = transpile_str("fn f() { let w = Widget::new(); }");
        assert!(out.contains("Widget::new_()"));
    }

    #[test]
    fn test_impl_const() {
        let out = transpile_str(
            r#"
            struct C {}
            impl C {
                const MAX: i32 = 100;
            }
        "#,
        );
        assert!(out.contains("static constexpr int32_t MAX = 100;"));
    }

    // ── extern "C" and unsafe tests ─────────────────────────────

    #[test]
    fn test_extern_c_function() {
        let out = transpile_str(r#"extern "C" fn add(a: i32, b: i32) -> i32 { a + b }"#);
        assert!(out.contains("extern \"C\" int32_t add("));
    }

    #[test]
    fn test_extern_c_block() {
        let out = transpile_str(
            r#"
            extern "C" {
                fn c_malloc(size: usize) -> *mut u8;
                fn c_free(ptr: *mut u8);
            }
        "#,
        );
        assert!(out.contains("extern \"C\" {"));
        assert!(out.contains("uint8_t* c_malloc(size_t size);"));
        assert!(out.contains("void c_free(uint8_t* ptr);"));
    }

    #[test]
    fn test_unsafe_block() {
        let out = transpile_str("fn f() { unsafe { let x = 1; } }");
        assert!(out.contains("// unsafe"));
        assert!(out.contains("const auto x = 1;"));
    }

    // ── Tuple and destructuring tests ───────────────────────────

    #[test]
    fn test_tuple_destructuring() {
        let out = transpile_str("fn f() { let (a, b) = pair; }");
        assert!(out.contains("auto [a, b] = pair;"));
    }

    #[test]
    fn test_tuple_expression() {
        let out = transpile_str("fn f() { let t = (1, 2, 3); }");
        assert!(out.contains("std::make_tuple(1, 2, 3)"));
    }

    #[test]
    fn test_typed_let_binding() {
        let out = transpile_str("fn f() { let x: i32 = 5; }");
        assert!(out.contains("const int32_t x = 5;"));
    }

    #[test]
    fn test_typed_let_mut_binding() {
        let out = transpile_str("fn f() { let mut x: i32 = 5; }");
        assert!(out.contains("int32_t x = 5;"));
        assert!(!out.contains("const"));
    }

    // ── Reference rebinding tests ───────────────────────────────

    #[test]
    fn test_ref_no_rebind_emits_reference() {
        let out = transpile_str("fn f() { let x = 5; let r = &x; }");
        assert!(out.contains("const auto& r = x;"));
    }

    #[test]
    fn test_ref_rebind_emits_pointer() {
        let out = transpile_str("fn f() { let x = 5; let y = 10; let mut r = &x; r = &y; }");
        assert!(out.contains("const auto* r = &x;"));
    }

    #[test]
    fn test_mut_ref_no_rebind_emits_reference() {
        let out = transpile_str("fn f() { let mut x = 5; let mr = &mut x; }");
        assert!(out.contains("auto& mr = x;"));
    }

    #[test]
    fn test_mut_ref_rebind_emits_pointer() {
        let out = transpile_str(
            "fn f() { let mut x = 5; let mut y = 10; let mut mr = &mut x; mr = &mut y; }",
        );
        assert!(out.contains("auto* mr = &x;"));
    }

    #[test]
    fn test_ref_rebind_in_if_branch() {
        // Rebinding inside if branch should still be detected
        let out = transpile_str(
            "fn f() { let x = 5; let y = 10; let mut r = &x; if true { r = &y; } }",
        );
        assert!(out.contains("const auto* r = &x;"));
    }

    #[test]
    fn test_ref_rebind_in_loop() {
        let out = transpile_str(
            "fn f() { let x = 5; let y = 10; let mut r = &x; loop { r = &y; break; } }",
        );
        assert!(out.contains("const auto* r = &x;"));
    }

    #[test]
    fn test_no_rebind_mut_binding_stays_reference() {
        // let mut r = &x with no reassignment → reference, not pointer
        let out = transpile_str("fn f() { let x = 5; let mut r = &x; }");
        assert!(out.contains("auto& r = x;") || out.contains("const auto& r = x;"));
        assert!(!out.contains("auto* r"));
    }

    // ── Implicit move insertion tests ───────────────────────────

    #[test]
    fn test_move_on_variable_binding() {
        // let b = a → auto b = std::move(a)
        let out = transpile_str("fn f() { let a = 1; let b = a; }");
        assert!(out.contains("std::move(a)"));
    }

    #[test]
    fn test_move_on_function_call_arg() {
        // consume(x) → consume(std::move(x))
        let out = transpile_str("fn f() { let x = 1; consume(x); }");
        assert!(out.contains("consume(std::move(x))"));
    }

    #[test]
    fn test_move_on_method_call_arg() {
        // v.push(item) → v.push(std::move(item))
        let out = transpile_str("fn f() { let item = 1; v.push(item); }");
        assert!(out.contains("v.push(std::move(item))"));
    }

    #[test]
    fn test_no_move_on_literal() {
        let out = transpile_str("fn f() { let x = 42; consume(42); }");
        assert!(!out.contains("std::move(42)"));
        assert!(out.contains("consume(42)"));
    }

    #[test]
    fn test_no_move_on_reference() {
        // &x should NOT be wrapped in move
        let out = transpile_str("fn f() { let x = 1; let r = &x; }");
        assert!(out.contains("const auto& r = x;"));
        assert!(!out.contains("std::move"));
    }

    #[test]
    fn test_no_move_on_ref_arg() {
        // borrow(&x) should not move — the & creates a reference
        let out = transpile_str("fn f() { let x = 1; borrow(&x); }");
        assert!(!out.contains("std::move(&x)"));
    }

    #[test]
    fn test_no_move_on_constant() {
        // ALL_CAPS names are constants, not moved
        let out = transpile_str("fn f() { let x = MAX_SIZE; }");
        assert!(!out.contains("std::move(MAX_SIZE)"));
    }

    #[test]
    fn test_no_move_on_type_name() {
        // Uppercase names are types/constructors, not moved
        let out = transpile_str("fn f() { let x = Default; }");
        assert!(!out.contains("std::move(Default)"));
    }

    #[test]
    fn test_no_move_on_bool() {
        let out = transpile_str("fn f() { let x = true; }");
        assert!(!out.contains("std::move"));
    }

    #[test]
    fn test_no_move_on_none() {
        let out = transpile_str("fn f() { let x = None; }");
        assert!(!out.contains("std::move"));
    }

    #[test]
    fn test_move_multiple_args() {
        let out = transpile_str("fn f() { let a = 1; let b = 2; process(a, b); }");
        assert!(out.contains("process(std::move(a), std::move(b))"));
    }

    #[test]
    fn test_no_move_on_expression() {
        // Complex expressions produce temporaries — no need for std::move
        let out = transpile_str("fn f() { let x = a + b; }");
        assert!(!out.contains("std::move(a + b)"));
        // But the individual variables a and b don't get moved in a binary expr
        // because binary ops borrow their operands
    }

    // ── Phase 2: Standard library type mapping tests ────────────

    #[test]
    fn test_str_param() {
        let out = transpile_str("fn f(s: &str) {}");
        assert!(out.contains("std::string_view s"));
    }

    #[test]
    fn test_box_new_mapping() {
        let out = transpile_str("fn f() { let b = Box::new(42); }");
        assert!(out.contains("rusty::Box::make(42)"));
    }

    #[test]
    fn test_string_from_mapping() {
        let out = transpile_str(r#"fn f() { let s = String::from("hello"); }"#);
        assert!(out.contains("rusty::String::from("));
    }

    #[test]
    fn test_vec_new_mapping() {
        let out = transpile_str("fn f() { let v = Vec::new(); }");
        assert!(out.contains("rusty::Vec::new_()"));
    }

    #[test]
    fn test_condvar_type() {
        let out = transpile_str("fn f(cv: Condvar) {}");
        assert!(out.contains("rusty::Condvar cv"));
    }

    #[test]
    fn test_barrier_type() {
        let out = transpile_str("fn f(b: Barrier) {}");
        assert!(out.contains("rusty::Barrier b"));
    }

    #[test]
    fn test_once_type() {
        let out = transpile_str("fn f(o: Once) {}");
        assert!(out.contains("rusty::Once o"));
    }

    #[test]
    fn test_nested_generic_types() {
        let out = transpile_str("fn f(v: Vec<Option<String>>) {}");
        assert!(out.contains("rusty::Vec<rusty::Option<rusty::String>>"));
    }

    #[test]
    fn test_arc_mutex_nested() {
        let out = transpile_str("fn f(m: Arc<Mutex<i32>>) {}");
        assert!(out.contains("rusty::Arc<rusty::Mutex<int32_t>>"));
    }

    #[test]
    fn test_rc_type() {
        let out = transpile_str("fn f(r: Rc<i32>) {}");
        assert!(out.contains("rusty::Rc<int32_t>"));
    }

    #[test]
    fn test_weak_type() {
        let out = transpile_str("fn f(w: Weak<i32>) {}");
        assert!(out.contains("rusty::Weak<int32_t>"));
    }

    #[test]
    fn test_cell_type() {
        let out = transpile_str("fn f(c: Cell<i32>) {}");
        assert!(out.contains("rusty::Cell<int32_t>"));
    }

    #[test]
    fn test_refcell_type() {
        let out = transpile_str("fn f(r: RefCell<String>) {}");
        assert!(out.contains("rusty::RefCell<rusty::String>"));
    }

    #[test]
    fn test_vecdeque_type() {
        let out = transpile_str("fn f(d: VecDeque<i32>) {}");
        assert!(out.contains("rusty::VecDeque<int32_t>"));
    }

    #[test]
    fn test_btreemap_type() {
        let out = transpile_str("fn f(m: BTreeMap<i32, String>) {}");
        assert!(out.contains("rusty::BTreeMap<int32_t, rusty::String>"));
    }

    #[test]
    fn test_maybe_uninit_type() {
        let out = transpile_str("fn f(m: MaybeUninit<i32>) {}");
        assert!(out.contains("rusty::MaybeUninit<int32_t>"));
    }

    // ── Phase 3: Match expression tests ─────────────────────────

    #[test]
    fn test_match_int_switch() {
        let out = transpile_str("fn f(x: i32) { match x { 1 => { a(); } 2 => { b(); } _ => { c(); } } }");
        assert!(out.contains("switch (x) {"));
        assert!(out.contains("case 1: {"));
        assert!(out.contains("case 2: {"));
        assert!(out.contains("default: {"));
        assert!(out.contains("break;"));
    }

    #[test]
    fn test_match_multi_pattern() {
        let out = transpile_str("fn f(x: i32) { match x { 1 | 2 | 3 => { ok(); } _ => {} } }");
        assert!(out.contains("case 1:"));
        assert!(out.contains("case 2:"));
        assert!(out.contains("case 3: {"));
    }

    #[test]
    fn test_match_enum_visit() {
        let out = transpile_str(
            r#"
            enum E { A(i32), B }
            fn f(e: E) { match e { E::A(x) => { use_x(x); } E::B => { b(); } } }
        "#,
        );
        assert!(out.contains("std::visit(overloaded {"));
        assert!(out.contains("[](const E_A& _v)"));
        assert!(out.contains("const auto& x = _v._0;"));
        assert!(out.contains("[](const E_B&)"));
    }

    #[test]
    fn test_match_struct_variant() {
        let out = transpile_str(
            r#"
            enum M { Point { x: f64, y: f64 } }
            fn f(m: M) { match m { M::Point { x, y } => { use_point(x, y); } } }
        "#,
        );
        assert!(out.contains("[](const M_Point& _v)"));
        assert!(out.contains("const auto& x = _v.x;"));
        assert!(out.contains("const auto& y = _v.y;"));
    }

    #[test]
    fn test_match_wildcard_arm() {
        let out = transpile_str(
            r#"
            enum E { A(i32), B }
            fn f(e: E) { match e { E::A(x) => { a(); } _ => { other(); } } }
        "#,
        );
        assert!(out.contains("[](const auto&) {"));
        assert!(out.contains("other();"));
    }

    #[test]
    fn test_match_with_guard() {
        let out = transpile_str(
            "fn f(x: i32) { match x { n if n > 0 => { pos(); } _ => { neg(); } } }",
        );
        // Guard should use if-else inside the case
        assert!(out.contains("if ("));
    }

    #[test]
    fn test_match_unit_variant() {
        let out = transpile_str(
            r#"
            enum E { A, B, C }
            fn f(e: E) { match e { E::A => { a(); } E::B => { b(); } E::C => { c(); } } }
        "#,
        );
        assert!(out.contains("std::visit(overloaded {"));
        assert!(out.contains("[](const E_A&)"));
        assert!(out.contains("[](const E_B&)"));
        assert!(out.contains("[](const E_C&)"));
    }

    #[test]
    fn test_match_catch_all_binding() {
        let out = transpile_str(
            r#"
            enum E { A(i32), B }
            fn f(e: E) { match e { E::A(x) => { a(); } other => { b(); } } }
        "#,
        );
        assert!(out.contains("[](const auto& other)"));
    }
}
