# CMake generated Testfile for 
# Source directory: /home/shuai/git/janus/third-party/rusty-cpp
# Build directory: /home/shuai/git/janus/third-party/rusty-cpp
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(rusty_arc_test "/home/shuai/git/janus/third-party/rusty-cpp/rusty_arc_test.out")
set_tests_properties(rusty_arc_test PROPERTIES  _BACKTRACE_TRIPLES "/home/shuai/git/janus/third-party/rusty-cpp/CMakeLists.txt;61;add_test;/home/shuai/git/janus/third-party/rusty-cpp/CMakeLists.txt;0;")
add_test(rusty_box_test "/home/shuai/git/janus/third-party/rusty-cpp/rusty_box_test.out")
set_tests_properties(rusty_box_test PROPERTIES  _BACKTRACE_TRIPLES "/home/shuai/git/janus/third-party/rusty-cpp/CMakeLists.txt;61;add_test;/home/shuai/git/janus/third-party/rusty-cpp/CMakeLists.txt;0;")
add_test(rusty_cell_test "/home/shuai/git/janus/third-party/rusty-cpp/rusty_cell_test.out")
set_tests_properties(rusty_cell_test PROPERTIES  _BACKTRACE_TRIPLES "/home/shuai/git/janus/third-party/rusty-cpp/CMakeLists.txt;61;add_test;/home/shuai/git/janus/third-party/rusty-cpp/CMakeLists.txt;0;")
add_test(rusty_option_test "/home/shuai/git/janus/third-party/rusty-cpp/rusty_option_test.out")
set_tests_properties(rusty_option_test PROPERTIES  _BACKTRACE_TRIPLES "/home/shuai/git/janus/third-party/rusty-cpp/CMakeLists.txt;61;add_test;/home/shuai/git/janus/third-party/rusty-cpp/CMakeLists.txt;0;")
add_test(rusty_rc_test "/home/shuai/git/janus/third-party/rusty-cpp/rusty_rc_test.out")
set_tests_properties(rusty_rc_test PROPERTIES  _BACKTRACE_TRIPLES "/home/shuai/git/janus/third-party/rusty-cpp/CMakeLists.txt;61;add_test;/home/shuai/git/janus/third-party/rusty-cpp/CMakeLists.txt;0;")
add_test(rusty_refcell_test "/home/shuai/git/janus/third-party/rusty-cpp/rusty_refcell_test.out")
set_tests_properties(rusty_refcell_test PROPERTIES  _BACKTRACE_TRIPLES "/home/shuai/git/janus/third-party/rusty-cpp/CMakeLists.txt;61;add_test;/home/shuai/git/janus/third-party/rusty-cpp/CMakeLists.txt;0;")
add_test(rusty_result_test "/home/shuai/git/janus/third-party/rusty-cpp/rusty_result_test.out")
set_tests_properties(rusty_result_test PROPERTIES  _BACKTRACE_TRIPLES "/home/shuai/git/janus/third-party/rusty-cpp/CMakeLists.txt;61;add_test;/home/shuai/git/janus/third-party/rusty-cpp/CMakeLists.txt;0;")
add_test(rusty_vec_test "/home/shuai/git/janus/third-party/rusty-cpp/rusty_vec_test.out")
set_tests_properties(rusty_vec_test PROPERTIES  _BACKTRACE_TRIPLES "/home/shuai/git/janus/third-party/rusty-cpp/CMakeLists.txt;61;add_test;/home/shuai/git/janus/third-party/rusty-cpp/CMakeLists.txt;0;")
add_test(test_traits "/home/shuai/git/janus/third-party/rusty-cpp/test_traits.out")
set_tests_properties(test_traits PROPERTIES  _BACKTRACE_TRIPLES "/home/shuai/git/janus/third-party/rusty-cpp/CMakeLists.txt;61;add_test;/home/shuai/git/janus/third-party/rusty-cpp/CMakeLists.txt;0;")
add_test(test_mutex "/home/shuai/git/janus/third-party/rusty-cpp/test_mutex.out")
set_tests_properties(test_mutex PROPERTIES  _BACKTRACE_TRIPLES "/home/shuai/git/janus/third-party/rusty-cpp/CMakeLists.txt;61;add_test;/home/shuai/git/janus/third-party/rusty-cpp/CMakeLists.txt;0;")
add_test(test_thread "/home/shuai/git/janus/third-party/rusty-cpp/test_thread.out")
set_tests_properties(test_thread PROPERTIES  _BACKTRACE_TRIPLES "/home/shuai/git/janus/third-party/rusty-cpp/CMakeLists.txt;61;add_test;/home/shuai/git/janus/third-party/rusty-cpp/CMakeLists.txt;0;")
add_test(test_channel "/home/shuai/git/janus/third-party/rusty-cpp/test_channel.out")
set_tests_properties(test_channel PROPERTIES  _BACKTRACE_TRIPLES "/home/shuai/git/janus/third-party/rusty-cpp/CMakeLists.txt;61;add_test;/home/shuai/git/janus/third-party/rusty-cpp/CMakeLists.txt;0;")
add_test(test_external_annotations "/home/shuai/git/janus/third-party/rusty-cpp/test_external_annotations.out")
set_tests_properties(test_external_annotations PROPERTIES  _BACKTRACE_TRIPLES "/home/shuai/git/janus/third-party/rusty-cpp/CMakeLists.txt;61;add_test;/home/shuai/git/janus/third-party/rusty-cpp/CMakeLists.txt;0;")
add_test(test_simplified_external "/home/shuai/git/janus/third-party/rusty-cpp/test_simplified_external.out")
set_tests_properties(test_simplified_external PROPERTIES  _BACKTRACE_TRIPLES "/home/shuai/git/janus/third-party/rusty-cpp/CMakeLists.txt;61;add_test;/home/shuai/git/janus/third-party/rusty-cpp/CMakeLists.txt;0;")
add_test(test_stl_lifetimes "/home/shuai/git/janus/third-party/rusty-cpp/test_stl_lifetimes.out")
set_tests_properties(test_stl_lifetimes PROPERTIES  _BACKTRACE_TRIPLES "/home/shuai/git/janus/third-party/rusty-cpp/CMakeLists.txt;61;add_test;/home/shuai/git/janus/third-party/rusty-cpp/CMakeLists.txt;0;")
add_test(test_unified_annotations "/home/shuai/git/janus/third-party/rusty-cpp/test_unified_annotations.out")
set_tests_properties(test_unified_annotations PROPERTIES  _BACKTRACE_TRIPLES "/home/shuai/git/janus/third-party/rusty-cpp/CMakeLists.txt;61;add_test;/home/shuai/git/janus/third-party/rusty-cpp/CMakeLists.txt;0;")
add_test(rusty_btreemap_test "/home/shuai/git/janus/third-party/rusty-cpp/rusty_btreemap_test.out")
set_tests_properties(rusty_btreemap_test PROPERTIES  _BACKTRACE_TRIPLES "/home/shuai/git/janus/third-party/rusty-cpp/CMakeLists.txt;61;add_test;/home/shuai/git/janus/third-party/rusty-cpp/CMakeLists.txt;0;")
add_test(rusty_hashmap_test "/home/shuai/git/janus/third-party/rusty-cpp/rusty_hashmap_test.out")
set_tests_properties(rusty_hashmap_test PROPERTIES  _BACKTRACE_TRIPLES "/home/shuai/git/janus/third-party/rusty-cpp/CMakeLists.txt;61;add_test;/home/shuai/git/janus/third-party/rusty-cpp/CMakeLists.txt;0;")
add_test(rusty_hashset_test "/home/shuai/git/janus/third-party/rusty-cpp/rusty_hashset_test.out")
set_tests_properties(rusty_hashset_test PROPERTIES  _BACKTRACE_TRIPLES "/home/shuai/git/janus/third-party/rusty-cpp/CMakeLists.txt;61;add_test;/home/shuai/git/janus/third-party/rusty-cpp/CMakeLists.txt;0;")
add_test(rusty_btreeset_test "/home/shuai/git/janus/third-party/rusty-cpp/rusty_btreeset_test.out")
set_tests_properties(rusty_btreeset_test PROPERTIES  _BACKTRACE_TRIPLES "/home/shuai/git/janus/third-party/rusty-cpp/CMakeLists.txt;61;add_test;/home/shuai/git/janus/third-party/rusty-cpp/CMakeLists.txt;0;")
