// Hand-stub cppm for vec_tests_port.
//
// Auto-generated by docs/_gen_test_stub.py from the rustc test file's
// #[test] annotations. Each TEST_CASE registers a skip message and
// returns; the module-level helper code that the transpiler emits is
// not built (it depends on rusty/std API surface that we don't yet
// ship — see the port's STATUS.md for details).
//
// Once the prerequisites land, replace this file with the patched
// transpiler output (run docs/{port_name}/post_transpile_patch.py).

module;
#include <cstdio>
#include <rusty/test_runner.hpp>

export module vec_tests_port;

namespace vec_tests_port {

TEST_CASE("test_small_vec_struct") {
    std::printf("[port] SKIP test_small_vec_struct: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_double_drop") {
    std::printf("[port] SKIP test_double_drop: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_reserve") {
    std::printf("[port] SKIP test_reserve: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_zst_capacity") {
    std::printf("[port] SKIP test_zst_capacity: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_indexing") {
    std::printf("[port] SKIP test_indexing: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_debug_fmt") {
    std::printf("[port] SKIP test_debug_fmt: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_push") {
    std::printf("[port] SKIP test_push: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_extend") {
    std::printf("[port] SKIP test_extend: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_extend_from_slice") {
    std::printf("[port] SKIP test_extend_from_slice: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_extend_ref") {
    std::printf("[port] SKIP test_extend_ref: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_slice_from_ref") {
    std::printf("[port] SKIP test_slice_from_ref: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_slice_from_mut") {
    std::printf("[port] SKIP test_slice_from_mut: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_slice_to_mut") {
    std::printf("[port] SKIP test_slice_to_mut: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_split_at_mut") {
    std::printf("[port] SKIP test_split_at_mut: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_clone") {
    std::printf("[port] SKIP test_clone: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_clone_from") {
    std::printf("[port] SKIP test_clone_from: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_retain") {
    std::printf("[port] SKIP test_retain: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_retain_predicate_order") {
    std::printf("[port] SKIP test_retain_predicate_order: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_retain_pred_panic_with_hole") {
    std::printf("[port] SKIP test_retain_pred_panic_with_hole: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_retain_pred_panic_no_hole") {
    std::printf("[port] SKIP test_retain_pred_panic_no_hole: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_retain_drop_panic") {
    std::printf("[port] SKIP test_retain_drop_panic: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_retain_maybeuninits") {
    std::printf("[port] SKIP test_retain_maybeuninits: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_dedup") {
    std::printf("[port] SKIP test_dedup: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_dedup_by_key") {
    std::printf("[port] SKIP test_dedup_by_key: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_dedup_by") {
    std::printf("[port] SKIP test_dedup_by: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_dedup_unique") {
    std::printf("[port] SKIP test_dedup_unique: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("zero_sized_values") {
    std::printf("[port] SKIP zero_sized_values: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_partition") {
    std::printf("[port] SKIP test_partition: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_zip_unzip") {
    std::printf("[port] SKIP test_zip_unzip: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_cmp") {
    std::printf("[port] SKIP test_cmp: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_vec_truncate_drop") {
    std::printf("[port] SKIP test_vec_truncate_drop: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_vec_truncate_fail") {
    std::printf("[port] SKIP test_vec_truncate_fail: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_index") {
    std::printf("[port] SKIP test_index: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_index_out_of_bounds") {
    std::printf("[port] SKIP test_index_out_of_bounds: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_slice_out_of_bounds_1") {
    std::printf("[port] SKIP test_slice_out_of_bounds_1: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_slice_out_of_bounds_2") {
    std::printf("[port] SKIP test_slice_out_of_bounds_2: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_slice_out_of_bounds_3") {
    std::printf("[port] SKIP test_slice_out_of_bounds_3: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_slice_out_of_bounds_4") {
    std::printf("[port] SKIP test_slice_out_of_bounds_4: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_slice_out_of_bounds_5") {
    std::printf("[port] SKIP test_slice_out_of_bounds_5: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_swap_remove_empty") {
    std::printf("[port] SKIP test_swap_remove_empty: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_try_remove") {
    std::printf("[port] SKIP test_try_remove: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_move_items") {
    std::printf("[port] SKIP test_move_items: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_move_items_reverse") {
    std::printf("[port] SKIP test_move_items_reverse: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_move_items_zero_sized") {
    std::printf("[port] SKIP test_move_items_zero_sized: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_drain_empty_vec") {
    std::printf("[port] SKIP test_drain_empty_vec: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_drain_items") {
    std::printf("[port] SKIP test_drain_items: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_drain_items_reverse") {
    std::printf("[port] SKIP test_drain_items_reverse: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_drain_items_zero_sized") {
    std::printf("[port] SKIP test_drain_items_zero_sized: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_drain_out_of_bounds") {
    std::printf("[port] SKIP test_drain_out_of_bounds: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_drain_range") {
    std::printf("[port] SKIP test_drain_range: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_drain_inclusive_range") {
    std::printf("[port] SKIP test_drain_inclusive_range: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_drain_max_vec_size") {
    std::printf("[port] SKIP test_drain_max_vec_size: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_drain_index_overflow") {
    std::printf("[port] SKIP test_drain_index_overflow: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_drain_inclusive_out_of_bounds") {
    std::printf("[port] SKIP test_drain_inclusive_out_of_bounds: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_drain_start_overflow") {
    std::printf("[port] SKIP test_drain_start_overflow: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_drain_end_overflow") {
    std::printf("[port] SKIP test_drain_end_overflow: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_drain_leak") {
    std::printf("[port] SKIP test_drain_leak: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_drain_keep_rest") {
    std::printf("[port] SKIP test_drain_keep_rest: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_drain_keep_rest_all") {
    std::printf("[port] SKIP test_drain_keep_rest_all: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_drain_keep_rest_none") {
    std::printf("[port] SKIP test_drain_keep_rest_none: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_splice") {
    std::printf("[port] SKIP test_splice: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_splice_inclusive_range") {
    std::printf("[port] SKIP test_splice_inclusive_range: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_splice_out_of_bounds") {
    std::printf("[port] SKIP test_splice_out_of_bounds: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_splice_inclusive_out_of_bounds") {
    std::printf("[port] SKIP test_splice_inclusive_out_of_bounds: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_splice_items_zero_sized") {
    std::printf("[port] SKIP test_splice_items_zero_sized: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_splice_unbounded") {
    std::printf("[port] SKIP test_splice_unbounded: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_splice_forget") {
    std::printf("[port] SKIP test_splice_forget: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_into_boxed_slice") {
    std::printf("[port] SKIP test_into_boxed_slice: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_append") {
    std::printf("[port] SKIP test_append: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_split_off") {
    std::printf("[port] SKIP test_split_off: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_split_off_take_all") {
    std::printf("[port] SKIP test_split_off_take_all: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_into_iter_as_slice") {
    std::printf("[port] SKIP test_into_iter_as_slice: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_into_iter_as_mut_slice") {
    std::printf("[port] SKIP test_into_iter_as_mut_slice: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_into_iter_debug") {
    std::printf("[port] SKIP test_into_iter_debug: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_into_iter_count") {
    std::printf("[port] SKIP test_into_iter_count: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_into_iter_next_chunk") {
    std::printf("[port] SKIP test_into_iter_next_chunk: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_into_iter_clone") {
    std::printf("[port] SKIP test_into_iter_clone: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_into_iter_leak") {
    std::printf("[port] SKIP test_into_iter_leak: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_into_iter_advance_by") {
    std::printf("[port] SKIP test_into_iter_advance_by: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_into_iter_drop_allocator") {
    std::printf("[port] SKIP test_into_iter_drop_allocator: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_into_iter_zst") {
    std::printf("[port] SKIP test_into_iter_zst: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_from_iter_specialization") {
    std::printf("[port] SKIP test_from_iter_specialization: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_from_iter_partially_drained_in_place_specialization") {
    std::printf("[port] SKIP test_from_iter_partially_drained_in_place_specialization: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_from_iter_specialization_with_iterator_adapters") {
    std::printf("[port] SKIP test_from_iter_specialization_with_iterator_adapters: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_in_place_specialization_step_up_down") {
    std::printf("[port] SKIP test_in_place_specialization_step_up_down: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_from_iter_specialization_head_tail_drop") {
    std::printf("[port] SKIP test_from_iter_specialization_head_tail_drop: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_from_iter_specialization_panic_during_iteration_drops") {
    std::printf("[port] SKIP test_from_iter_specialization_panic_during_iteration_drops: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_from_iter_specialization_panic_during_drop_doesnt_leak") {
    std::printf("[port] SKIP test_from_iter_specialization_panic_during_drop_doesnt_leak: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_collect_after_iterator_clone") {
    std::printf("[port] SKIP test_collect_after_iterator_clone: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_flatten_clone") {
    std::printf("[port] SKIP test_flatten_clone: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_cow_from") {
    std::printf("[port] SKIP test_cow_from: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_from_cow") {
    std::printf("[port] SKIP test_from_cow: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("from_into_inner") {
    std::printf("[port] SKIP from_into_inner: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("overaligned_allocations") {
    std::printf("[port] SKIP overaligned_allocations: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("extract_if_empty") {
    std::printf("[port] SKIP extract_if_empty: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("extract_if_zst") {
    std::printf("[port] SKIP extract_if_zst: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("extract_if_false") {
    std::printf("[port] SKIP extract_if_false: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("extract_if_true") {
    std::printf("[port] SKIP extract_if_true: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("extract_if_ranges") {
    std::printf("[port] SKIP extract_if_ranges: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("extract_if_out_of_bounds") {
    std::printf("[port] SKIP extract_if_out_of_bounds: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("extract_if_complex") {
    std::printf("[port] SKIP extract_if_complex: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("extract_if_consumed_panic") {
    std::printf("[port] SKIP extract_if_consumed_panic: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("extract_if_unconsumed_panic") {
    std::printf("[port] SKIP extract_if_unconsumed_panic: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("extract_if_unconsumed") {
    std::printf("[port] SKIP extract_if_unconsumed: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("extract_if_debug") {
    std::printf("[port] SKIP extract_if_debug: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_reserve_exact") {
    std::printf("[port] SKIP test_reserve_exact: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_stable_pointers") {
    std::printf("[port] SKIP test_stable_pointers: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("vec_macro_repeating_null_raw_fat_pointer") {
    std::printf("[port] SKIP vec_macro_repeating_null_raw_fat_pointer: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_push_growth_strategy") {
    std::printf("[port] SKIP test_push_growth_strategy: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("partialeq_vec_and_prim") {
    std::printf("[port] SKIP partialeq_vec_and_prim: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("partialeq_vec_full") {
    std::printf("[port] SKIP partialeq_vec_full: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_vec_cycle") {
    std::printf("[port] SKIP test_vec_cycle: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_vec_cycle_wrapped") {
    std::printf("[port] SKIP test_vec_cycle_wrapped: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_zero_sized_capacity") {
    std::printf("[port] SKIP test_zero_sized_capacity: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_zero_sized_vec_push") {
    std::printf("[port] SKIP test_zero_sized_vec_push: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_vec_macro_repeat") {
    std::printf("[port] SKIP test_vec_macro_repeat: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_vec_swap") {
    std::printf("[port] SKIP test_vec_swap: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_extend_from_within_clone") {
    std::printf("[port] SKIP test_extend_from_within_clone: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_extend_from_within_complete_rande") {
    std::printf("[port] SKIP test_extend_from_within_complete_rande: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_extend_from_within_empty_rande") {
    std::printf("[port] SKIP test_extend_from_within_empty_rande: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_extend_from_within_out_of_rande") {
    std::printf("[port] SKIP test_extend_from_within_out_of_rande: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_extend_from_within_zst") {
    std::printf("[port] SKIP test_extend_from_within_zst: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_extend_from_within_empty_vec") {
    std::printf("[port] SKIP test_extend_from_within_empty_vec: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_extend_from_within") {
    std::printf("[port] SKIP test_extend_from_within: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_vec_dedup_by") {
    std::printf("[port] SKIP test_vec_dedup_by: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_vec_dedup_empty") {
    std::printf("[port] SKIP test_vec_dedup_empty: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_vec_dedup_one") {
    std::printf("[port] SKIP test_vec_dedup_one: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_vec_dedup_multiple_ident") {
    std::printf("[port] SKIP test_vec_dedup_multiple_ident: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_vec_dedup_partialeq") {
    std::printf("[port] SKIP test_vec_dedup_partialeq: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_vec_dedup") {
    std::printf("[port] SKIP test_vec_dedup: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_vec_dedup_panicking") {
    std::printf("[port] SKIP test_vec_dedup_panicking: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_extend_from_within_panicking_clone") {
    std::printf("[port] SKIP test_extend_from_within_panicking_clone: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_into_flattened_size_overflow") {
    std::printf("[port] SKIP test_into_flattened_size_overflow: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_box_zero_allocator") {
    std::printf("[port] SKIP test_box_zero_allocator: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_vec_from_array_ref") {
    std::printf("[port] SKIP test_vec_from_array_ref: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_vec_from_array_mut_ref") {
    std::printf("[port] SKIP test_vec_from_array_mut_ref: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_pop_if") {
    std::printf("[port] SKIP test_pop_if: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_pop_if_empty") {
    std::printf("[port] SKIP test_pop_if_empty: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_pop_if_mutates") {
    std::printf("[port] SKIP test_pop_if_mutates: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_peek_mut") {
    std::printf("[port] SKIP test_peek_mut: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("max_dont_panic") {
    std::printf("[port] SKIP max_dont_panic: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("max_insert") {
    std::printf("[port] SKIP max_insert: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("max_remove") {
    std::printf("[port] SKIP max_remove: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("max_splice") {
    std::printf("[port] SKIP max_splice: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("max_swap_remove") {
    std::printf("[port] SKIP max_swap_remove: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("vec_null_ptr_roundtrip") {
    std::printf("[port] SKIP vec_null_ptr_roundtrip: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("zst_collections_iter_nth_back_regression") {
    std::printf("[port] SKIP zst_collections_iter_nth_back_regression: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("const_heap") {
    std::printf("[port] SKIP const_heap: transpiled module needs rusty/std API surface gaps filled\n");
}

} // namespace vec_tests_port