// Hand-stub cppm for rc_tests_port.
//
// Auto-generated by docs/_gen_test_stub.py from the rustc test file's
// #[test] annotations. Each TEST_CASE registers a skip message and
// returns; the module-level helper code that the transpiler emits is
// not built (it depends on rusty/std API surface that we don't yet
// ship — see the port's STATUS.md for details).
//
// Once the prerequisites land, replace this file with the patched
// transpiler output (run docs/{port_name}/post_transpile_patch.py).

module;
#include <cstdio>
#include <rusty/test_runner.hpp>

export module rc_tests_port;

namespace rc_tests_port {

TEST_CASE("uninhabited") {
    std::printf("[port] SKIP uninhabited: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("slice") {
    std::printf("[port] SKIP slice: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("trait_object") {
    std::printf("[port] SKIP trait_object: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("float_nan_ne") {
    std::printf("[port] SKIP float_nan_ne: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("partial_eq") {
    std::printf("[port] SKIP partial_eq: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("eq") {
    std::printf("[port] SKIP eq: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("shared_from_iter_normal") {
    std::printf("[port] SKIP shared_from_iter_normal: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("shared_from_iter_trustedlen_normal") {
    std::printf("[port] SKIP shared_from_iter_trustedlen_normal: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("shared_from_iter_trustedlen_panic") {
    std::printf("[port] SKIP shared_from_iter_trustedlen_panic: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("shared_from_iter_trustedlen_no_fuse") {
    std::printf("[port] SKIP shared_from_iter_trustedlen_no_fuse: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("weak_may_dangle") {
    std::printf("[port] SKIP weak_may_dangle: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("panic_no_leak") {
    std::printf("[port] SKIP panic_no_leak: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_clone") {
    std::printf("[port] SKIP test_clone: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_simple") {
    std::printf("[port] SKIP test_simple: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_simple_clone") {
    std::printf("[port] SKIP test_simple_clone: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_destructor") {
    std::printf("[port] SKIP test_destructor: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_live") {
    std::printf("[port] SKIP test_live: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_dead") {
    std::printf("[port] SKIP test_dead: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("weak_self_cyclic") {
    std::printf("[port] SKIP weak_self_cyclic: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("is_unique") {
    std::printf("[port] SKIP is_unique: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_strong_count") {
    std::printf("[port] SKIP test_strong_count: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_weak_count") {
    std::printf("[port] SKIP test_weak_count: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("weak_counts") {
    std::printf("[port] SKIP weak_counts: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("try_unwrap") {
    std::printf("[port] SKIP try_unwrap: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("into_inner") {
    std::printf("[port] SKIP into_inner: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("into_from_raw") {
    std::printf("[port] SKIP into_from_raw: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_into_from_raw_unsized") {
    std::printf("[port] SKIP test_into_from_raw_unsized: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("into_from_weak_raw") {
    std::printf("[port] SKIP into_from_weak_raw: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_into_from_weak_raw_unsized") {
    std::printf("[port] SKIP test_into_from_weak_raw_unsized: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("get_mut") {
    std::printf("[port] SKIP get_mut: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_cowrc_clone_make_unique") {
    std::printf("[port] SKIP test_cowrc_clone_make_unique: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_cowrc_clone_unique2") {
    std::printf("[port] SKIP test_cowrc_clone_unique2: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_cowrc_clone_weak") {
    std::printf("[port] SKIP test_cowrc_clone_weak: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_cowrc_unsized") {
    std::printf("[port] SKIP test_cowrc_unsized: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_show") {
    std::printf("[port] SKIP test_show: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_unsized") {
    std::printf("[port] SKIP test_unsized: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_maybe_thin_unsized") {
    std::printf("[port] SKIP test_maybe_thin_unsized: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_from_owned") {
    std::printf("[port] SKIP test_from_owned: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_new_weak") {
    std::printf("[port] SKIP test_new_weak: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_ptr_eq") {
    std::printf("[port] SKIP test_ptr_eq: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_from_str") {
    std::printf("[port] SKIP test_from_str: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_copy_from_slice") {
    std::printf("[port] SKIP test_copy_from_slice: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_clone_from_slice") {
    std::printf("[port] SKIP test_clone_from_slice: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_clone_from_slice_panic") {
    std::printf("[port] SKIP test_clone_from_slice_panic: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_from_box") {
    std::printf("[port] SKIP test_from_box: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_from_box_str") {
    std::printf("[port] SKIP test_from_box_str: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_from_box_slice") {
    std::printf("[port] SKIP test_from_box_slice: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_from_box_trait") {
    std::printf("[port] SKIP test_from_box_trait: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_from_box_trait_zero_sized") {
    std::printf("[port] SKIP test_from_box_trait_zero_sized: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_from_vec") {
    std::printf("[port] SKIP test_from_vec: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_downcast") {
    std::printf("[port] SKIP test_downcast: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_array_from_slice") {
    std::printf("[port] SKIP test_array_from_slice: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_rc_cyclic_with_zero_refs") {
    std::printf("[port] SKIP test_rc_cyclic_with_zero_refs: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_rc_cyclic_with_one_ref") {
    std::printf("[port] SKIP test_rc_cyclic_with_one_ref: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_rc_cyclic_with_two_ref") {
    std::printf("[port] SKIP test_rc_cyclic_with_two_ref: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_unique_rc_weak") {
    std::printf("[port] SKIP test_unique_rc_weak: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_unique_rc_drop_weak") {
    std::printf("[port] SKIP test_unique_rc_drop_weak: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_unique_rc_drops_contents") {
    std::printf("[port] SKIP test_unique_rc_drops_contents: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_unique_rc_with_alloc_drops_contents") {
    std::printf("[port] SKIP test_unique_rc_with_alloc_drops_contents: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_unique_rc_weak_clone_holding_ref") {
    std::printf("[port] SKIP test_unique_rc_weak_clone_holding_ref: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_unique_rc_unsizing_coercion") {
    std::printf("[port] SKIP test_unique_rc_unsizing_coercion: transpiled module needs rusty/std API surface gaps filled\n");
}

} // namespace rc_tests_port