// Auto-generated by rusty-cpp-transpiler
// Do not edit manually.

module;

#include <cstdint>
#include <cstddef>
#include <limits>
#include <variant>
#include <tuple>
#include <optional>
#include <utility>
#include <type_traits>
#include <typeindex>
#include <any>
#include <string>
#include <string_view>
#include <charconv>
#include <cstdlib>
#include <bit>
#include <stdexcept>
#include <rusty/try.hpp>

#if defined(__GNUC__)
#pragma GCC diagnostic ignored "-Wunused-local-typedefs"
#endif

export module test_autotrait;
import rusty;

// extern crate std

// extern crate test

template<typename T>
void assert_send_sync();
void test();

// Rust-only: using namespace std::prelude::rust_2018;

// Rust-only libtest metadata const skipped: test (marker: test, should_panic: no)

template<typename T>
void assert_send_sync() {
}

void test() {
    ::assert_send_sync<BuildMetadata>();
    ::assert_send_sync<Comparator>();
    ::assert_send_sync<Error>();
    ::assert_send_sync<Prerelease>();
    ::assert_send_sync<Version>();
    ::assert_send_sync<VersionReq>();
    ::assert_send_sync<Op>();
}

// Rust-only libtest main omitted


// Runnable wrappers for expanded Rust test bodies
// Rust-only libtest wrapper metadata: marker=test should_panic=no
export void rusty_test_test() {
    test();
}
