// Hand-stub cppm for arc_tests_port.
//
// Auto-generated by docs/_gen_test_stub.py from the rustc test file's
// #[test] annotations. Each TEST_CASE registers a skip message and
// returns; the module-level helper code that the transpiler emits is
// not built (it depends on rusty/std API surface that we don't yet
// ship — see the port's STATUS.md for details).
//
// Once the prerequisites land, replace this file with the patched
// transpiler output (run docs/{port_name}/post_transpile_patch.py).

module;
#include <cstdio>
#include <rusty/test_runner.hpp>

export module arc_tests_port;

namespace arc_tests_port {

TEST_CASE("uninhabited") {
    std::printf("[port] SKIP uninhabited: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("slice") {
    std::printf("[port] SKIP slice: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("trait_object") {
    std::printf("[port] SKIP trait_object: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("float_nan_ne") {
    std::printf("[port] SKIP float_nan_ne: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("partial_eq") {
    std::printf("[port] SKIP partial_eq: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("eq") {
    std::printf("[port] SKIP eq: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("shared_from_iter_normal") {
    std::printf("[port] SKIP shared_from_iter_normal: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("shared_from_iter_trustedlen_normal") {
    std::printf("[port] SKIP shared_from_iter_trustedlen_normal: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("shared_from_iter_trustedlen_panic") {
    std::printf("[port] SKIP shared_from_iter_trustedlen_panic: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("shared_from_iter_trustedlen_no_fuse") {
    std::printf("[port] SKIP shared_from_iter_trustedlen_no_fuse: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("weak_may_dangle") {
    std::printf("[port] SKIP weak_may_dangle: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("panic_no_leak") {
    std::printf("[port] SKIP panic_no_leak: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("make_mut_unsized") {
    std::printf("[port] SKIP make_mut_unsized: transpiled module needs rusty/std API surface gaps filled\n");
}

TEST_CASE("test_unique_arc_weak") {
    std::printf("[port] SKIP test_unique_arc_weak: transpiled module needs rusty/std API surface gaps filled\n");
}

} // namespace arc_tests_port