// Auto-generated by rusty-cpp-transpiler
// Do not edit manually.

module;

#include <cstdint>
#include <cstddef>
#include <limits>
#include <variant>
#include <tuple>
#include <optional>
#include <utility>
#include <type_traits>
#include <typeindex>
#include <any>
#include <string>
#include <string_view>
#include <charconv>
#include <cstdlib>
#include <bit>
#include <stdexcept>
#include <print>
#include <immintrin.h>
#include <rusty/rusty.hpp>
#include <rusty/try.hpp>

#if defined(__GNUC__)
#pragma GCC diagnostic ignored "-Wunused-local-typedefs"
#endif

export module testing_port.macros;

// macro_rules! struct_with_counted_drop { ... }

// Rust-only macro import: using struct_with_counted_drop;

