// Auto-generated by rusty-cpp-transpiler
// Do not edit manually.

module;

#include <cstdint>
#include <cstddef>
#include <limits>
#include <variant>
#include <tuple>
#include <optional>
#include <utility>
#include <type_traits>
#include <typeindex>
#include <any>
#include <string>
#include <string_view>
#include <charconv>
#include <cstdlib>
#include <bit>
#include <stdexcept>
#include <print>
#include <immintrin.h>
#include <rusty/rusty.hpp>
#include <rusty/try.hpp>

#if defined(__GNUC__)
#pragma GCC diagnostic ignored "-Wunused-local-typedefs"
#endif

export module testing_port.rng;

export struct DeterministicRng;

/// XorShiftRng
export struct DeterministicRng {
    size_t count;
    uint32_t x;
    uint32_t y;
    uint32_t z;
    uint32_t w;

    static DeterministicRng new_();
    uint32_t next();
};


DeterministicRng DeterministicRng::new_() {
    return DeterministicRng{.count = static_cast<size_t>(0), .x = static_cast<uint32_t>(423257940), .y = static_cast<uint32_t>(2829571177), .z = static_cast<uint32_t>(2541948421), .w = static_cast<uint32_t>(289122235)};
}

uint32_t DeterministicRng::next() {
    this->count += 1;
    assert((rusty::detail::deref_if_pointer_like(this->count) <= 70029));
    const auto x = this->x;
    const auto t = rusty::detail::deref_if_pointer_like(x) ^ ((rusty::detail::deref_if_pointer_like(x) << 11));
    this->x = this->y;
    this->y = this->z;
    this->z = this->w;
    const auto w_ = this->w;
    this->w = (rusty::detail::deref_if_pointer_like(w_) ^ ((rusty::detail::deref_if_pointer_like(w_) >> 19))) ^ ((rusty::detail::deref_if_pointer_like(t) ^ ((rusty::detail::deref_if_pointer_like(t) >> 8))));
    return this->w;
}

