// Auto-generated by rusty-cpp-transpiler
// Do not edit manually.

module;

#include <cstdint>
#include <cstddef>
#include <limits>
#include <variant>
#include <tuple>
#include <optional>
#include <utility>
#include <type_traits>
#include <typeindex>
#include <any>
#include <string>
#include <string_view>
#include <charconv>
#include <cstdlib>
#include <cstdio>
#include <bit>
#include <cwctype>
#include <stdexcept>
#include <print>
#include <immintrin.h>
#include <rusty/rusty.hpp>
#include <rusty/test_runner.hpp>
#include <rusty/try.hpp>

#if defined(__GNUC__)
#pragma GCC diagnostic ignored "-Wunused-local-typedefs"
#endif

export module btree_set_hash_tests_port;
import btree_port.btree.set;



namespace btree_set_hash_tests_port {

using ::btree_port::btree::set::BTreeSet;

// Rust-only namespace re-export: using hash;

// alloctests' `fn hash<T: Hash>(t: &T) -> u64` helper, over the port's
// emitted Hash protocol (`t.hash(state)`) and rusty::hash::SipHasher.
template <typename T>
static uint64_t hash(const T& t) {
    rusty::hash::SipHasher s;
    t.hash(s);
    return s.finish();
}
// Rust hashes `&(&x, &y)` — a tuple of REFERENCES. The emitted
// make_tuple would COPY the (move-only) sets; hash the pair in
// sequence instead, mirroring tuple Hash (element-wise, no length).
template <typename A, typename B>
static uint64_t hash_pair(const A& a, const B& b) {
    rusty::hash::SipHasher s;
    a.hash(s);
    b.hash(s);
    return s.finish();
}


TEST_CASE("test_hash") {
    auto x = ::btree_port::btree::set::BTreeSet<int32_t>::new_();
    auto y = ::btree_port::btree::set::BTreeSet<int32_t>::new_();
    x.insert(1);
    x.insert(2);
    x.insert(3);
    y.insert(3);
    y.insert(2);
    y.insert(1);
    assert(((hash(x)) == (hash(y))));
}

TEST_CASE("test_prefix_free") {
    const auto x = ::btree_port::btree::set::BTreeSet<int32_t>::from(std::array{1, 2, 3});
    const auto y = ::btree_port::btree::set::BTreeSet<int32_t>::new_();
    assert(((hash_pair(x, y)) != (hash_pair(y, x))));
}

} // namespace btree_set_hash_tests_port
