// Inline Rust DSL example in a .cpp file.
// V1 rule: this stays local to this translation unit unless declarations are
// surfaced manually in headers or module interfaces.

#if RUSTYCPP_RUST
fn add(a: i32, b: i32) -> i32 {
    a + b
}
#endif
/*RUSTYCPP:GEN-BEGIN id=cmake_example.local.add version=1 rust_sha256=49395200c39034710abc77ad3d14a97a8d3be18a92994f8f03eeddc2021aa172*/
// Auto-generated by rusty-cpp-transpiler
// Do not edit manually.

#include <cstdint>
#include <cstddef>
#include <limits>
#include <variant>
#include <tuple>
#include <optional>
#include <utility>
#include <type_traits>
#include <typeindex>
#include <any>
#include <string>
#include <string_view>
#include <charconv>
#include <cstdlib>
#include <bit>
#include <stdexcept>
#include <rusty/rusty.hpp>
#include <rusty/try.hpp>

#if defined(__GNUC__)
#pragma GCC diagnostic ignored "-Wunused-local-typedefs"
#endif

int32_t add(int32_t a, int32_t b);

int32_t add(int32_t a, int32_t b) {
    return rusty::detail::deref_if_pointer_like(a) + rusty::detail::deref_if_pointer_like(b);
}

/*RUSTYCPP:GEN-END id=cmake_example.local.add*/
