#pragma once

// Inline Rust DSL example in a header-like file.
// V1 rule: this is safe for shared APIs because other translation units can include it.

#if RUSTYCPP_RUST
pub fn greet(name: &str) -> String {
    let mut out = String::from("Hello, ");
    out.push_str(name);
    out
}
#endif
/*RUSTYCPP:GEN-BEGIN id=cmake_example.header.greet version=1 rust_sha256=9271c3b2f57fe08ec09db694c8c1d9a081f4055c8132b48f3cbfdb823cb6be02*/
// Auto-generated by rusty-cpp-transpiler
// Do not edit manually.

#include <cstdint>
#include <cstddef>
#include <limits>
#include <variant>
#include <tuple>
#include <optional>
#include <utility>
#include <type_traits>
#include <typeindex>
#include <any>
#include <string>
#include <string_view>
#include <charconv>
#include <cstdlib>
#include <bit>
#include <stdexcept>
#include <rusty/rusty.hpp>
#include <rusty/try.hpp>

#if defined(__GNUC__)
#pragma GCC diagnostic ignored "-Wunused-local-typedefs"
#endif

rusty::String greet(std::string_view name);

rusty::String greet(std::string_view name) {
    auto out = rusty::String::from("Hello, ");
    out.push_str(name);
    return std::move(out);
}

/*RUSTYCPP:GEN-END id=cmake_example.header.greet*/
