#pragma once

// Inline Rust DSL example in a header-like file.
// V1 rule: this is safe for shared APIs because other translation units can include it.

#if RUSTYCPP_RUST
pub fn greet(name: &str) -> String {
    let mut out = String::from("Hello, ");
    out.push_str(name);
    out
}
#endif
/*RUSTYCPP:GEN-BEGIN id=cmake_example.header.greet version=1 rust_sha256=9271c3b2f57fe08ec09db694c8c1d9a081f4055c8132b48f3cbfdb823cb6be02*/
// generated by rusty-cpp-transpiler inline-rust v1
// inline-rust-v1: fallback stub; semantic lowering is not yet implemented
// rust payload (normalized) line count: 5
/*RUSTYCPP:GEN-END id=cmake_example.header.greet*/
