// Inline Rust DSL example in a .cpp file.
// V1 rule: this stays local to this translation unit unless declarations are
// surfaced manually in headers or module interfaces.

#if RUSTYCPP_RUST
/*RUSTYCPP:RUST-BEGIN id=cmake_example.local.add*/
@rust {
fn add(a: i32, b: i32) -> i32 {
    a + b
}
}
/*RUSTYCPP:RUST-END id=cmake_example.local.add*/
#else
/*RUSTYCPP:GEN-BEGIN id=cmake_example.local.add version=1 rust_sha256=49395200c39034710abc77ad3d14a97a8d3be18a92994f8f03eeddc2021aa172*/
// generated by rusty-cpp-transpiler inline-rust v1
// inline-rust-v1: fallback stub; semantic lowering is not yet implemented
// rust payload (normalized) line count: 3
/*RUSTYCPP:GEN-END id=cmake_example.local.add*/
#endif

