// Auto-generated by rusty-cpp-transpiler
// Do not edit manually.
// Phase A2: stub — advanced feature, body skipped.
module;
#include <cstdint>
#include <rusty/rusty.hpp>
export module hashbrown_port.rustc_entry;
