#!/usr/bin/env python3
"""Generate a hand-stub .cppm for a rustc test file where the transpiled
module-level helper code doesn't compile yet.

Extracts every `#[test]` (and `#[should_panic]`) function name from the
Rust source and emits a TEST_CASE skip block for each.

Usage:
    python3 docs/_gen_test_stub.py <rust_src> <port_name> <out_cppm>

Example:
    python3 docs/_gen_test_stub.py ~/.rustup/.../vec.rs vec_tests_port \\
        transpiled/vec_tests_port/vec_tests_port.cppm
"""
from __future__ import annotations
import argparse
import re
import sys
from pathlib import Path


def extract_test_names(rust_src: Path) -> list[str]:
    """Return [(name, kind)] for every #[test] / #[should_panic] fn."""
    text = rust_src.read_text()
    # Match `#[test]` (possibly followed by other attrs), then `fn NAME(`.
    # We allow other attributes between `#[test]` and `fn`.
    pattern = re.compile(
        r'#\[test\][^a-zA-Z_]*?(?:#\[[^\]]+\][^a-zA-Z_]*?)*?fn\s+([a-zA-Z_][a-zA-Z0-9_]*)',
        re.DOTALL,
    )
    return list(pattern.findall(text))


def emit_stub_cppm(port_name: str, test_names: list[str], reason: str) -> str:
    lines = [
        f"// Hand-stub cppm for {port_name}.",
        "//",
        "// Auto-generated by docs/_gen_test_stub.py from the rustc test file's",
        "// #[test] annotations. Each TEST_CASE registers a skip message and",
        "// returns; the module-level helper code that the transpiler emits is",
        "// not built (it depends on rusty/std API surface that we don't yet",
        f"// ship — see the port's STATUS.md for details).",
        "//",
        "// Once the prerequisites land, replace this file with the patched",
        "// transpiler output (run docs/{port_name}/post_transpile_patch.py).",
        "",
        "module;",
        "#include <cstdio>",
        "#include <rusty/test_runner.hpp>",
        "",
        f"export module {port_name};",
        "",
        f"namespace {port_name} {{",
        "",
    ]
    for name in test_names:
        lines.append(f'TEST_CASE("{name}") {{')
        lines.append(f'    std::printf("[port] SKIP {name}: {reason}\\n");')
        lines.append("}")
        lines.append("")
    lines.append(f"}} // namespace {port_name}")
    return "\n".join(lines)


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("rust_src", type=Path)
    p.add_argument("port_name")
    p.add_argument("out_cppm", type=Path)
    p.add_argument(
        "--reason",
        default="transpiled module needs rusty/std API surface gaps filled",
    )
    args = p.parse_args()

    names = extract_test_names(args.rust_src)
    if not names:
        print(f"warn: no #[test] found in {args.rust_src}", file=sys.stderr)
    out = emit_stub_cppm(args.port_name, names, args.reason)
    args.out_cppm.parent.mkdir(parents=True, exist_ok=True)
    args.out_cppm.write_text(out)
    print(f"emitted {args.out_cppm} with {len(names)} test stub(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
