// Auto-generated by rusty-cpp-transpiler
// Do not edit manually.

module;

#include <cstdint>
#include <cstddef>
#include <limits>
#include <variant>
#include <tuple>
#include <optional>
#include <utility>
#include <type_traits>
#include <typeindex>
#include <any>
#include <string>
#include <string_view>
#include <charconv>
#include <cstdlib>
#include <bit>
#include <stdexcept>
#include <print>
#include <immintrin.h>
#include <rusty/rusty.hpp>
#include <rusty/test_runner.hpp>
#include <rusty/try.hpp>

#if defined(__GNUC__)
#pragma GCC diagnostic ignored "-Wunused-local-typedefs"
#endif

export module linked_list_tests_port;

// patcher-injected module imports:
import linked_list_port;

namespace linked_list_tests_port {

// Rust-only: using std::collections::LinkedList;

TEST_CASE("test_hash") {
    /* PATCHED: skipped */
    std::printf("[port] SKIP test_hash: needs std::hash builder (rusty-cpp infra gap)\n");
    return;
}

} // namespace linked_list_tests_port
